import { NextResponse } from "next/server";
import crypto from "crypto";
import { getRazorpayWebhookSecret } from "@/lib/razorpay/server";
import { createAdminClient } from "@/lib/supabase/admin";
export const dynamic="force-dynamic";
type RazorpayWebhookPayload={event?:string;payload?:{subscription?:{entity?:{id?:string;status?:string;current_start?:number;current_end?:number;notes?:Record<string,string>}};payment?:{entity?:{id?:string;subscription_id?:string;order_id?:string;notes?:Record<string,string>}};order?:{entity?:{id?:string;status?:string;notes?:Record<string,string>}}}};
function verifyWebhookSignature(body:string,signature:string,secret:string){const expectedSignature=crypto.createHmac("sha256",secret).update(body).digest("hex");const expected=Buffer.from(expectedSignature,"utf8");const received=Buffer.from(signature,"utf8");return expected.length===received.length&&crypto.timingSafeEqual(expected,received);}
export async function POST(request:Request){try{const rawBody=await request.text();if(!rawBody)return NextResponse.json({error:"Empty webhook body."},{status:400});const signature=request.headers.get("x-razorpay-signature");if(!signature)return NextResponse.json({error:"Missing webhook signature."},{status:401});const webhookSecret=getRazorpayWebhookSecret();if(!verifyWebhookSignature(rawBody,signature,webhookSecret))return NextResponse.json({error:"Invalid webhook signature."},{status:401});const payload=JSON.parse(rawBody) as RazorpayWebhookPayload;const eventType=payload.event;if(!eventType)return NextResponse.json({error:"Missing event type."},{status:400});const eventId=crypto.createHash("sha256").update(`${signature}:${rawBody}`).digest("hex");const admin=createAdminClient();const {data:existingEvent,error:existingEventError}=await admin.from("razorpay_webhook_events").select("id").eq("razorpay_event_id",eventId).maybeSingle();if(existingEventError)return NextResponse.json({error:"Unable to process webhook."},{status:500});if(existingEvent)return NextResponse.json({success:true,duplicate:true});
 const subscriptionEntity=payload.payload?.subscription?.entity;const paymentEntity=payload.payload?.payment?.entity;const orderEntity=payload.payload?.order?.entity;const razorpaySubscriptionId=subscriptionEntity?.id||paymentEntity?.subscription_id;const paymentId=paymentEntity?.id;const notesUserId=subscriptionEntity?.notes?.user_id||paymentEntity?.notes?.user_id;let userId:string|null=notesUserId||null;if(!userId&&razorpaySubscriptionId){const {data:subscriptionRow}=await admin.from("subscriptions").select("user_id").eq("razorpay_subscription_id",razorpaySubscriptionId).maybeSingle();userId=subscriptionRow?.user_id??null;}
 if(userId){const razorpayStatus=subscriptionEntity?.status;let status:"active"|"cancelled"|"expired"|null=null;if(eventType==="subscription.activated"||eventType==="subscription.charged"||eventType==="payment.captured")status="active";else if(eventType==="subscription.cancelled")status="cancelled";else if(eventType==="subscription.completed"||eventType==="subscription.halted")status="expired";else if(razorpayStatus==="active")status="active";if(status){const currentPeriodStart=subscriptionEntity?.current_start?new Date(subscriptionEntity.current_start*1000).toISOString():new Date().toISOString();const currentPeriodEnd=subscriptionEntity?.current_end?new Date(subscriptionEntity.current_end*1000).toISOString():new Date(Date.now()+30*24*60*60*1000).toISOString();const isPro=status==="active";await admin.from("subscriptions").upsert({user_id:userId,razorpay_subscription_id:razorpaySubscriptionId??null,plan:isPro?"pro":"free",status,current_period_start:currentPeriodStart,current_period_end:currentPeriodEnd,last_payment_id:paymentId??undefined,updated_at:new Date().toISOString()},{onConflict:"user_id"});if(!isPro)await admin.from("profiles").update({ghost_mode:false}).eq("id",userId);}}
 const shopOrderId=orderEntity?.notes?.shop_order_id||paymentEntity?.notes?.shop_order_id;const razorpayOrderId=orderEntity?.id||paymentEntity?.order_id;if((eventType==="order.paid"||eventType==="payment.captured")&&(shopOrderId||razorpayOrderId)){const query=shopOrderId?admin.from("shop_orders").select("id").eq("id",shopOrderId):admin.from("shop_orders").select("id").eq("razorpay_order_id",razorpayOrderId as string);const {data:shopOrder}=await query.maybeSingle();if(shopOrder){if(paymentId)await admin.from("shop_orders").update({razorpay_payment_id:paymentId,updated_at:new Date().toISOString()}).eq("id",shopOrder.id);const {error}=await admin.rpc("fulfill_shop_order",{p_order_id:shopOrder.id});if(error){console.error("Shop webhook fulfillment failed:",error);return NextResponse.json({error:"Shop fulfillment failed."},{status:500});}}}
 await admin.from("razorpay_webhook_events").insert({razorpay_event_id:eventId,event_type:eventType});return NextResponse.json({success:true});}catch(error){console.error("Razorpay webhook error:",error);return NextResponse.json({error:"Webhook processing failed."},{status:500});}}
