import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { Users, MapPin, ShieldCheck, Heart, MessageCircle, UserPlus, Inbox, Compass } from "lucide-react";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { routes } from "@/config/routes";
import { getProfilePhotoUrl } from "@/lib/profile-photo";
import { Button } from "@/components/ui/button";
import { ConnectButton, AcceptButton } from "./social-actions";

export const metadata:Metadata={title:"Explore | Extrovert"}; export const dynamic="force-dynamic";
type SocialProfile={id:string;display_name:string|null;bio:string|null;interests:string[]|null;area_id:string|null;verification_status:string|null;area_verification_status:string|null;profile_photo_path:string|null}; type Connection={id:string;requester_id:string;target_id:string;status:string};

export default async function SocialPage(){
 const supabase=await createServerSupabaseClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)return null;
 const {data:me}=await supabase.from("extrovert_profiles").select("display_name,area_id,verification_status,area_verification_status").eq("id",user.id).maybeSingle(); const areaId=me?.area_id??null;
 const [{data:area},{data:people},{data:connections}]=await Promise.all([areaId?supabase.from("extrovert_areas").select("name").eq("id",areaId).maybeSingle():Promise.resolve({data:null}),areaId?supabase.from("extrovert_profiles").select("id,display_name,bio,interests,area_id,verification_status,area_verification_status,profile_photo_path").eq("area_id",areaId).neq("id",user.id).neq("trust_state","banned").order("verification_status",{ascending:false}).limit(12):Promise.resolve({data:[]}),supabase.from("extrovert_connections").select("id,requester_id,target_id,status").or(`requester_id.eq.${user.id},target_id.eq.${user.id}`)]);
 const all=(connections??[]) as Connection[]; const connectionMap=new Map<string,Connection>(); for(const c of all){connectionMap.set(c.requester_id===user.id?c.target_id:c.requester_id,c);} const incoming=all.filter(c=>c.target_id===user.id&&c.status==="pending"); const accepted=all.filter(c=>c.status==="accepted"); const conversationIds=accepted.map(c=>c.id); const {data:conversationRows}=conversationIds.length?await supabase.from("extrovert_conversations").select("id,connection_id").in("connection_id",conversationIds):{data:[]}; const conversationMap=new Map((conversationRows??[]).map((c:{id:string;connection_id:string})=>[c.connection_id,c.id])); const profiles=(people??[]) as SocialProfile[]; const areaName=area?.name??"Your area";
 return <main className="mx-auto w-full max-w-md px-4 pb-24 pt-20 font-sans text-zinc-950 md:max-w-3xl md:pt-5"><header className="flex items-end justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-emerald-600"><Compass className="mr-1 inline h-3.5 w-3.5"/>Explore</p><h1 className="mt-1 text-3xl font-black tracking-tight">Your social world</h1><p className="mt-1 text-xs text-zinc-500">Find people around you and connect when it feels right.</p></div><Link href={routes.discover}><Button size="sm" className="rounded-full bg-emerald-600 text-white"><Heart className="mr-1.5 h-3.5 w-3.5"/>Swipe</Button></Link></header>
 <section className="mt-5 rounded-[2rem] border border-emerald-100 bg-emerald-50/60 p-3"><div className="relative h-64 overflow-hidden rounded-[1.5rem] border border-emerald-100 bg-white"><div className="absolute inset-0 opacity-40" style={{backgroundImage:"linear-gradient(rgba(16,185,129,.10) 1px,transparent 1px),linear-gradient(90deg,rgba(16,185,129,.10) 1px,transparent 1px)",backgroundSize:"42px 42px"}}/>{profiles.slice(0,10).map((profile,index)=>{const positions=[[18,30],[38,22],[62,30],[78,20],[28,58],[52,50],[72,62],[14,74],[46,78],[84,72]][index];const photo=getProfilePhotoUrl(profile.profile_photo_path,96);return <Link key={profile.id} href={`${routes.profileView}/${profile.id}`} className="absolute grid h-11 w-11 -translate-x-1/2 -translate-y-1/2 place-items-center overflow-hidden rounded-full border-2 border-white bg-emerald-100 shadow-sm" style={{left:`${positions[0]}%`,top:`${positions[1]}%`}}>{photo?<Image src={photo} alt="" fill sizes="44px" className="object-cover"/>:<span className="text-xs font-black text-emerald-700">{profile.display_name?.charAt(0)??"?"}</span>}</Link>})}<div className="absolute bottom-3 left-3 rounded-full bg-white px-3 py-1.5 text-[10px] font-bold text-zinc-700 shadow-sm"><MapPin className="mr-1 inline h-3 w-3 text-emerald-600"/>{areaName} · {profiles.length} nearby</div><div className="absolute right-3 top-3 rounded-full bg-white px-3 py-1.5 text-[9px] font-bold text-zinc-500 shadow-sm">Approximate area</div></div><div className="mt-3 grid grid-cols-3 gap-2"><div className="rounded-2xl bg-white p-3"><MapPin className="h-4 w-4 text-emerald-600"/><p className="mt-2 text-xs font-black">{areaName}</p><p className="text-[9px] text-zinc-500">Selected area</p></div><div className="rounded-2xl bg-white p-3"><ShieldCheck className="h-4 w-4 text-emerald-600"/><p className="mt-2 text-xs font-black">{me?.verification_status==="verified"?"Verified":"Not verified"}</p><p className="text-[9px] text-zinc-500">Identity</p></div><div className="rounded-2xl bg-white p-3"><Users className="h-4 w-4 text-emerald-600"/><p className="mt-2 text-xs font-black">{profiles.length}</p><p className="text-[9px] text-zinc-500">Nearby</p></div></div></section>
 {incoming.length>0&&<section className="mt-4 rounded-3xl border border-emerald-100 bg-white p-4"><div className="mb-3 flex items-center gap-2"><Inbox className="h-4 w-4 text-emerald-600"/><h2 className="text-sm font-black">Friend requests ({incoming.length})</h2></div><div className="space-y-2">{incoming.map(c=><div key={c.id} className="flex items-center justify-between gap-3 rounded-2xl bg-emerald-50 p-3"><div><p className="text-xs font-black">New friend request</p><p className="text-[9px] text-zinc-500">Accept to start social chat.</p></div><AcceptButton connectionId={c.id}/></div>)}</div></section>}
 <section className="mt-6"><div className="mb-3 flex items-end justify-between"><div><p className="text-[10px] font-black uppercase tracking-wider text-emerald-600">People nearby</p><h2 className="text-lg font-black">Meet your area</h2></div><span className="text-[10px] font-bold text-zinc-400">{profiles.length} shown</span></div>{profiles.length===0?<div className="rounded-3xl border border-dashed border-zinc-200 bg-white p-8 text-center"><Users className="mx-auto h-7 w-7 text-zinc-300"/><h3 className="mt-3 text-sm font-black">No one nearby yet</h3><p className="mt-1 text-xs text-zinc-500">New people appear as they join your area.</p></div>:<div className="grid gap-2.5 sm:grid-cols-2">{profiles.map(profile=>{const c=connectionMap.get(profile.id);const photo=getProfilePhotoUrl(profile.profile_photo_path,320);const conversationId=c?.status==="accepted"?conversationMap.get(c.id):null;return <article key={profile.id} className="flex gap-3 rounded-3xl border border-zinc-200 bg-white p-3 shadow-sm"><div className="relative h-20 w-20 shrink-0 overflow-hidden rounded-2xl bg-emerald-50">{photo?<Image src={photo} alt={profile.display_name??"Person"} fill sizes="80px" className="object-cover"/>:<div className="grid h-full place-items-center text-xl font-black text-emerald-300">{profile.display_name?.charAt(0)??"?"}</div>}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-1.5"><h3 className="truncate text-sm font-black">{profile.display_name??"Extrovert member"}</h3>{profile.verification_status==="verified"&&<ShieldCheck className="h-3.5 w-3.5 text-emerald-600"/>}</div><p className="mt-1 line-clamp-2 text-[10px] leading-4 text-zinc-500">{profile.bio||"Open to meeting new people."}</p>{profile.interests?.length?<p className="mt-1 truncate text-[9px] font-semibold text-emerald-700">{profile.interests.slice(0,3).join(" · ")}</p>:null}<div className="mt-2 flex gap-1.5">{c?.status==="accepted"&&conversationId?<Link href={`/app/messages/social/${conversationId}`}><Button size="sm" variant="outline"><MessageCircle className="mr-1 h-3 w-3"/>Chat</Button></Link>:c?.status==="accepted"?<span className="rounded-lg bg-zinc-100 px-2 py-1 text-[9px] font-bold text-zinc-500">Connected</span>:c?.status==="pending"?<span className="rounded-lg bg-zinc-100 px-2 py-1 text-[9px] font-bold text-zinc-500">Request sent</span>:<ConnectButton targetId={profile.id}/>}</div></div></article>})}</div>}</section>
 <section className="mt-6 rounded-3xl border border-zinc-200 bg-white p-4"><div className="flex items-center gap-2"><UserPlus className="h-4 w-4 text-emerald-600"/><h2 className="text-sm font-black">Friends & social</h2></div><p className="mt-1 text-[10px] leading-4 text-zinc-500">Dating stays the focus. Use Explore when you want friends, local people and social connections.</p></section>
 </main>;
}
