import Link from "next/link";
import { ArrowUpRight, Heart, ShieldCheck, Sparkles } from "lucide-react";
import { routes } from "@/config/routes";

const columns=[
 {title:"Extrovert",links:[{href:routes.discover,label:"Dating"},{href:routes.social,label:"Social"},{href:routes.likes,label:"Likes"},{href:routes.messages,label:"Chat"},{href:routes.profile,label:"Profile"}]},
 {title:"Trust",links:[{href:routes.safety,label:"Safety"},{href:routes.privacy,label:"Privacy"},{href:routes.terms,label:"Terms"},{href:routes.identityVerification,label:"Identity verification"}]},
 {title:"More",links:[{href:routes.about,label:"About"},{href:routes.extrovert,label:"Extrovert Plus"},{href:routes.register,label:"Get started"}]},
];
export function Footer(){return <footer className="border-t border-zinc-200 bg-white font-sans text-zinc-900"><div className="mx-auto max-w-6xl px-5 py-12 sm:px-6"><div className="grid gap-10 border-b border-zinc-100 pb-10 sm:grid-cols-2 lg:grid-cols-[1.4fr_2fr]"><div><Link href={routes.home} className="inline-flex items-center gap-2.5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-600 text-white"><Heart className="h-4 w-4 fill-current"/></span><span className="text-lg font-black tracking-tight">Extrovert<span className="text-emerald-600">.</span></span></Link><p className="mt-4 max-w-sm text-xs leading-5 text-zinc-500">Dating and Social in one place. Meet people, make connections and stay in control of your profile.</p><div className="mt-4 inline-flex items-center gap-1.5 rounded-full border border-emerald-100 bg-emerald-50 px-3 py-1.5 text-[10px] font-bold text-emerald-700"><ShieldCheck className="h-3.5 w-3.5"/> Trust and safety built in</div></div><div className="grid grid-cols-2 gap-8 sm:grid-cols-3">{columns.map(column=><div key={column.title}><p className="text-[10px] font-black uppercase tracking-[.16em] text-zinc-950">{column.title}</p><ul className="mt-3 space-y-2.5">{column.links.map(link=><li key={link.href}><Link href={link.href} className="inline-flex items-center gap-1 text-xs font-semibold text-zinc-500 hover:text-emerald-700">{link.label}<ArrowUpRight className="h-3 w-3 opacity-0 transition-opacity group-hover:opacity-100"/></Link></li>)}</ul></div>)}</div></div><div className="flex flex-col gap-3 pt-6 text-[10px] font-semibold text-zinc-400 sm:flex-row sm:items-center sm:justify-between"><span>© {new Date().getFullYear()} Extrovert. All rights reserved.</span><span className="inline-flex items-center gap-1.5"><Sparkles className="h-3 w-3 text-emerald-600"/>Made for real connections.</span></div></div></footer>}
