"use server";

import { revalidatePath } from "next/cache";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { routes } from "@/config/routes";
import { isUuid } from "@/lib/validation";
import { sendPushToUser } from "@/lib/push/server";

export type LikeResult={error:string|null;matched:boolean;matchId?:string};export type ActionResult={error:string|null;success?:boolean};

export async function likeProfile(profileId:string):Promise<LikeResult>{if(!isUuid(profileId))return{error:"Invalid profile.",matched:false};const supabase=await createServerSupabaseClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return{error:"You must be logged in to like someone.",matched:false};if(user.id===profileId)return{error:"You cannot like your own profile.",matched:false};const {data:result,error}=await supabase.rpc("like_profile",{p_profile_id:profileId});if(error){const message=error.message||"Couldn't save your like. Please try again.";if(message.includes("PROFILE_UNAVAILABLE"))return{error:"That profile is no longer available.",matched:false};if(message.includes("USER_UNAVAILABLE"))return{error:"This user is unavailable.",matched:false};if(message.includes("AUTH_REQUIRED"))return{error:"You must be logged in to like someone.",matched:false};if(message.includes("LIKE_LIMIT_REACHED"))return{error:"You're out of likes for now. Get more in the DateBu Shop or unlock Extrovert.",matched:false};return{error:"Couldn't save your like. Please try again.",matched:false};}const row=Array.isArray(result)?result[0]:result;const matched=Boolean(row?.matched);const matchId=row?.match_id??undefined;revalidatePath(routes.discover);if(matched&&matchId){revalidatePath(routes.matches);revalidatePath(routes.messages);}const {data:targetProfile}=await supabase.from("profiles").select("display_name").eq("id",profileId).maybeSingle();const targetName=targetProfile?.display_name||"someone";if(matched&&matchId){await Promise.all([sendPushToUser(profileId,{title:"It’s a Match!",body:"You matched on DateBu.",url:`${routes.messages}/${matchId}`,tag:`match-${matchId}`}),sendPushToUser(user.id,{title:"It’s a Match!",body:`You matched with ${targetName}.`,url:`${routes.messages}/${matchId}`,tag:`match-${matchId}`})]);}else await sendPushToUser(profileId,{title:"Someone likes you",body:"Someone liked your profile. Open DateBu to see who.",url:routes.discover,tag:`like-${user.id}`});return{error:null,matched,matchId};}

export async function superLikeProfile(profileId:string):Promise<ActionResult>{if(!isUuid(profileId))return{error:"Invalid profile."};const supabase=await createServerSupabaseClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return{error:"You must be logged in."};if(user.id===profileId)return{error:"You cannot Super Like yourself."};const {data:target}=await supabase.from("profiles").select("id,display_name").eq("id",profileId).eq("profile_completed",true).eq("ghost_mode",false).maybeSingle();if(!target)return{error:"That profile is no longer available."};const {data:blocked}=await supabase.from("blocks").select("id").or(`and(blocker_id.eq.${user.id},blocked_id.eq.${profileId}),and(blocker_id.eq.${profileId},blocked_id.eq.${user.id})`).maybeSingle();if(blocked)return{error:"You can't interact with this student."};const {data:wallet}=await supabase.from("superlike_wallets").select("purchased_superlikes").eq("user_id",user.id).maybeSingle();if(!wallet||wallet.purchased_superlikes<1)return{error:"You're out of Super Likes. Get more in the DateBu Shop."};const {error:insertError}=await supabase.from("superlikes").insert({sender_id:user.id,recipient_id:profileId});if(insertError?.code==="23505")return{error:"You've already Super Liked this profile."};if(insertError)return{error:"Couldn't send your Super Like. Please try again."};const {error:updateError}=await supabase.from("superlike_wallets").update({purchased_superlikes:wallet.purchased_superlikes-1,updated_at:new Date().toISOString()}).eq("user_id",user.id).gte("purchased_superlikes",1);if(updateError)return{error:"Super Like could not be completed. Please try again."};await sendPushToUser(profileId,{title:"Someone Super Liked you",body:"You received a Super Like on DateBu.",url:`${routes.profileView}/${user.id}`,tag:`superlike-${user.id}`});revalidatePath(routes.profile);return{error:null,success:true};}

export async function passProfile(profileId:string):Promise<ActionResult>{if(!isUuid(profileId))return{error:"Invalid profile."};const supabase=await createServerSupabaseClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return{error:"You must be logged in to pass someone."};if(user.id===profileId)return{error:"You cannot pass your own profile."};const {error}=await supabase.from("passes").insert({passer_id:user.id,passed_id:profileId});if(error&&error.code!=="23505")return{error:"Couldn't save your pass. Please try again."};revalidatePath(routes.discover);return{error:null,success:true};}

export async function rewindLastPass():Promise<ActionResult>{const supabase=await createServerSupabaseClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return{error:"You must be logged in."};const {data:isPro}=await supabase.rpc("is_datebu_pro");if(!isPro)return{error:"Rewind is a DateBu Extrovert feature."};const {data:lastPass}=await supabase.from("passes").select("id,passed_id").eq("passer_id",user.id).order("created_at",{ascending:false}).limit(1).maybeSingle();if(!lastPass)return{error:"There is nothing to rewind yet."};const {error}=await supabase.from("passes").delete().eq("id",lastPass.id).eq("passer_id",user.id);if(error)return{error:"Couldn't rewind that profile. Please try again."};revalidatePath(routes.discover);return{error:null,success:true};}

export async function resetPassedProfiles():Promise<ActionResult>{const supabase=await createServerSupabaseClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return{error:"You must be logged in."};const {error}=await supabase.from("passes").delete().eq("passer_id",user.id);if(error)return{error:"Couldn't bring back passed profiles. Please try again."};revalidatePath(routes.discover);return{error:null,success:true};}

export async function blockUser(targetUserId:string):Promise<ActionResult>{if(!isUuid(targetUserId))return{error:"Invalid profile."};const supabase=await createServerSupabaseClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return{error:"You must be logged in to block a user."};if(user.id===targetUserId)return{error:"You cannot block yourself."};const {error}=await supabase.from("blocks").insert({blocker_id:user.id,blocked_id:targetUserId});if(error&&error.code!=="23505")return{error:"Failed to block user. Please try again."};const [userA,userB]=user.id<targetUserId?[user.id,targetUserId]:[targetUserId,user.id];await supabase.from("matches").delete().eq("user_a",userA).eq("user_b",userB);revalidatePath(routes.discover);revalidatePath(routes.matches);revalidatePath(routes.messages);return{error:null,success:true};}

export async function unblockUser(targetUserId:string):Promise<ActionResult>{if(!isUuid(targetUserId))return{error:"Invalid profile."};const supabase=await createServerSupabaseClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return{error:"You must be logged in to unblock a user."};const {error}=await supabase.from("blocks").delete().eq("blocker_id",user.id).eq("blocked_id",targetUserId);if(error)return{error:"Failed to unblock user."};revalidatePath(routes.settings);revalidatePath(routes.discover);return{error:null,success:true};}

export async function reportUser(targetUserId:string,reason:string,details?:string):Promise<ActionResult>{if(!isUuid(targetUserId))return{error:"Invalid profile."};const supabase=await createServerSupabaseClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return{error:"You must be logged in to submit a report."};if(user.id===targetUserId)return{error:"You cannot report yourself."};if(!reason.trim())return{error:"Please select a reason for the report."};if(reason.trim().length>120||(details?.trim().length??0)>500)return{error:"Report details are too long."};const {error:reportError}=await supabase.from("reports").insert({reporter_id:user.id,reported_id:targetUserId,reason:reason.trim(),details:details?.trim()||null});if(reportError)return{error:"Failed to submit report. Please try again."};await supabase.from("blocks").upsert({blocker_id:user.id,blocked_id:targetUserId},{onConflict:"blocker_id,blocked_id"});revalidatePath(routes.discover);revalidatePath(routes.matches);return{error:null,success:true};}

export async function toggleGhostMode(enabled:boolean):Promise<ActionResult>{const supabase=await createServerSupabaseClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return{error:"You must be logged in."};const {data:isPro}=await supabase.rpc("is_datebu_pro");if(!isPro)return{error:"Ghost Mode is a DateBu Extrovert feature."};const {error}=await supabase.from("profiles").update({ghost_mode:enabled}).eq("id",user.id);if(error)return{error:"Failed to update ghost mode."};revalidatePath(routes.settings);revalidatePath(routes.profile);revalidatePath(routes.app);return{error:null,success:true};}
