"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import Link from "next/link";
import { motion, AnimatePresence, type PanInfo } from "framer-motion";
import { Heart, X, ShieldCheck, Sparkles, MessageCircle, MoreVertical, RotateCcw, SlidersHorizontal, UserRound, Loader2, Star, MapPin } from "lucide-react";
import { likeProfile, passProfile, rewindLastPass, resetPassedProfiles, blockUser, reportUser, superLikeProfile } from "./actions";
import { routes } from "@/config/routes";
import { Button } from "@/components/ui/button";
import { calculateAge } from "@/lib/utils";
import SuperChatComposer from "@/components/payments/superchat-composer";

type Interest={id:string;name:string}; type ProfileInterest={interests:Interest|Interest[]|null}; type ProfilePhoto={storage_path:string;display_order:number;is_primary:boolean;url?:string|null};
export type DiscoverProfile={id:string;display_name:string|null;date_of_birth:string|null;gender:string|null;department:string|null;academic_year:string|null;bio:string|null;profile_photos:ProfilePhoto[]|null;profile_interests:ProfileInterest[]|null;profile_photo_url:string|null;verification_status?:string|null;area_verification_status?:string|null;area_name?:string|null;identity_context?:string|null};
type Props={profiles:DiscoverProfile[];isPro?:boolean};
const swipeDistance=120;

export default function DiscoverClient({profiles,isPro=false}:Props){
 const router=useRouter(); const [deck,setDeck]=useState(profiles); const [busy,setBusy]=useState(false); const [toast,setToast]=useState<string|null>(null); const [match,setMatch]=useState<DiscoverProfile|null>(null); const [safety,setSafety]=useState<DiscoverProfile|null>(null); const [reporting,setReporting]=useState<DiscoverProfile|null>(null); const [reportReason,setReportReason]=useState("Inappropriate photo or content"); const [reportDetails,setReportDetails]=useState(""); const [superChat,setSuperChat]=useState<DiscoverProfile|null>(null);
 useEffect(()=>setDeck(profiles),[profiles]);
 const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(null),2200)};
 async function act(id:string,kind:"like"|"pass"|"super"){if(busy)return;const target=deck.find(p=>p.id===id);if(!target)return;setBusy(true);setDeck(current=>current.filter(p=>p.id!==id));try{const result=kind==="like"?await likeProfile(id):kind==="pass"?await passProfile(id):await superLikeProfile(id);if(result.error){setDeck(current=>[target,...current]);notify(result.error);}else if(kind==="like"&&"matched"in result&&result.matched){setMatch(target);}else if(kind==="super"){notify(`Super Like sent to ${target.display_name??"this person"}.`);}}catch{setDeck(current=>[target,...current]);notify("Something went wrong. Please try again.");}finally{setBusy(false)}}
 async function rewind(){if(!isPro||busy)return;setBusy(true);try{const result=await rewindLastPass();if(result.error)notify(result.error);else router.refresh();}finally{setBusy(false)}}
 async function reviewPassed(){if(busy)return;setBusy(true);try{const result=await resetPassedProfiles();if(result.error)notify(result.error);else if(!result.count)notify("No passed profiles to review yet.");else router.refresh();}finally{setBusy(false)}}
 async function block(){if(!safety)return;const id=safety.id;setSafety(null);const result=await blockUser(id);if(result.error)notify(result.error);else{setDeck(current=>current.filter(p=>p.id!==id));notify("Profile blocked.")}}
 async function report(event:React.FormEvent){event.preventDefault();if(!reporting)return;setBusy(true);const result=await reportUser(reporting.id,reportReason,reportDetails);setBusy(false);if(result.error)notify(result.error);else{setDeck(current=>current.filter(p=>p.id!==reporting.id));setReporting(null);setReportDetails("");notify("Report sent. This profile was removed.")}}
 const current=deck[0];
 if(!current&&!match)return <main className="mx-auto flex min-h-[calc(100dvh-68px)] w-full max-w-md items-center justify-center bg-white px-4 pb-20 pt-16 text-zinc-950"><section className="w-full rounded-[2rem] border border-emerald-100 bg-white p-7 text-center shadow-sm"><Sparkles className="mx-auto h-8 w-8 text-emerald-600"/><p className="mt-4 text-[10px] font-black uppercase tracking-[.18em] text-emerald-600">Discover</p><h1 className="mt-1 text-2xl font-black">You&apos;re all caught up</h1><p className="mx-auto mt-2 max-w-xs text-xs leading-5 text-zinc-500">New people will appear as they join. You can also review people you passed.</p><Button onClick={()=>void reviewPassed()} disabled={busy} className="mt-5 h-11 w-full rounded-2xl bg-emerald-600 text-white">{busy?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<RotateCcw className="mr-2 h-4 w-4"/>}Review passed</Button><Link href={routes.profileSetup} className="mt-2 flex h-11 items-center justify-center gap-2 rounded-2xl border border-zinc-200 text-xs font-black"><SlidersHorizontal className="h-3.5 w-3.5"/>Preferences</Link></section></main>;
 return <main className="relative mx-auto flex min-h-[calc(100dvh-68px)] w-full max-w-md flex-col bg-white px-3 pb-20 pt-16 text-zinc-950 md:px-4 md:pt-2">
  <AnimatePresence>{toast&&<motion.div initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} exit={{opacity:0}} className="fixed left-1/2 top-16 z-[120] -translate-x-1/2 rounded-full border border-emerald-100 bg-white px-4 py-2 text-xs font-bold text-zinc-800 shadow-lg">{toast}</motion.div>}</AnimatePresence>
  <div className="mb-2 flex items-end justify-between px-1"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-emerald-600">Discover</p><h1 className="text-2xl font-black tracking-tight">Find your people</h1></div><Link href={routes.profileSetup} aria-label="Dating preferences" className="grid h-9 w-9 place-items-center rounded-full border border-zinc-200 bg-white text-zinc-700"><SlidersHorizontal className="h-4 w-4"/></Link></div>
  <div className="relative min-h-0 flex-1"><div className="relative h-[min(68dvh,590px)] w-full overflow-visible md:h-[min(74dvh,650px)]">
   {deck.slice(0,2).map((profile,index)=><SwipeCard key={profile.id} profile={profile} top={index===0} onSwipe={(direction)=>void act(profile.id,direction==="right"?"like":"pass")} onSafety={()=>setSafety(profile)} onSuperChat={()=>setSuperChat(profile)}/>)}
  </div></div>
  {current&&<div className="mx-auto mt-3 flex items-center justify-center gap-2"><button onClick={()=>void rewind()} disabled={!isPro||busy} aria-label="Undo pass" className="grid h-11 w-11 place-items-center rounded-full border border-zinc-200 bg-white text-zinc-500 shadow-sm disabled:opacity-30"><RotateCcw className="h-4 w-4"/></button><button onClick={()=>void act(current.id,"pass")} disabled={busy} aria-label="Pass" className="grid h-14 w-14 place-items-center rounded-full border border-zinc-200 bg-white text-zinc-800 shadow-sm active:scale-95"><X className="h-6 w-6"/></button><button onClick={()=>void act(current.id,"like")} disabled={busy} aria-label="Like" className="grid h-[66px] w-[66px] place-items-center rounded-full bg-emerald-600 text-white shadow-lg shadow-emerald-200 active:scale-95 disabled:opacity-50"><Heart className="h-7 w-7 fill-current"/></button><button onClick={()=>void act(current.id,"super")} disabled={busy} aria-label="Super Like" className="grid h-14 w-14 place-items-center rounded-full border border-emerald-200 bg-white text-emerald-600 shadow-sm active:scale-95"><Star className="h-5 w-5 fill-current"/></button><Link href={`${routes.profileView}/${current.id}`} aria-label="View full profile" className="grid h-11 w-11 place-items-center rounded-full border border-zinc-200 bg-white text-zinc-700 shadow-sm"><UserRound className="h-5 w-5"/></Link></div>}
  <p className="mt-2 text-center text-[9px] font-semibold text-zinc-400">Swipe right to like · left to pass · tap SuperChat on a card to message first</p>
  <AnimatePresence>{safety&&<div className="fixed inset-0 z-[10000] grid place-items-center bg-zinc-950/30 p-4"><motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="w-full max-w-sm rounded-3xl bg-white p-5 shadow-xl"><div className="flex items-center justify-between"><b className="text-sm">Safety</b><button onClick={()=>setSafety(null)}><X className="h-5 w-5"/></button></div><div className="mt-4 grid gap-2"><Link href={`${routes.profileView}/${safety.id}`} onClick={()=>setSafety(null)} className="rounded-2xl border p-3 text-xs font-bold">View profile</Link><button onClick={()=>{setReporting(safety);setSafety(null)}} className="rounded-2xl border border-amber-200 bg-amber-50 p-3 text-left text-xs font-bold text-amber-700">Report profile</button><button onClick={()=>void block()} className="rounded-2xl border border-red-200 bg-red-50 p-3 text-left text-xs font-bold text-red-700">Block profile</button></div></motion.div></div>}</AnimatePresence>
  <AnimatePresence>{reporting&&<div className="fixed inset-0 z-[10001] grid place-items-center bg-zinc-950/30 p-4"><motion.form onSubmit={report} initial={{opacity:0,scale:.98}} animate={{opacity:1,scale:1}} className="w-full max-w-md rounded-3xl bg-white p-5 shadow-xl"><div className="flex items-center justify-between"><b className="text-base">Report profile</b><button type="button" onClick={()=>setReporting(null)}><X className="h-5 w-5"/></button></div><select value={reportReason} onChange={e=>setReportReason(e.target.value)} className="mt-4 w-full rounded-xl border border-zinc-200 p-3 text-xs"><option>Inappropriate photo or content</option><option>Harassment or abusive behavior</option><option>Fake or impersonated profile</option><option>Spam or commercial advertising</option><option>Underage user</option><option>Other safety concern</option></select><textarea value={reportDetails} onChange={e=>setReportDetails(e.target.value)} rows={4} maxLength={500} className="mt-3 w-full resize-none rounded-xl border border-zinc-200 p-3 text-xs" placeholder="What happened? (optional)"/><div className="mt-3 flex gap-2"><Button type="button" variant="secondary" onClick={()=>setReporting(null)} className="flex-1">Cancel</Button><Button disabled={busy} className="flex-1 bg-emerald-600 text-white">{busy?"Sending…":"Send report"}</Button></div></motion.form></div>}</AnimatePresence>
  <AnimatePresence>{match&&<div className="fixed inset-0 z-[10002] grid place-items-center bg-zinc-950/40 p-4"><motion.div initial={{opacity:0,scale:.92}} animate={{opacity:1,scale:1}} className="w-full max-w-sm rounded-[2rem] bg-white p-7 text-center shadow-xl"><div className="mx-auto grid h-20 w-20 place-items-center overflow-hidden rounded-full border-4 border-emerald-100 bg-emerald-50">{match.profile_photo_url?<Image src={match.profile_photo_url} alt="" width={80} height={80} className="h-full w-full object-cover"/>:<Heart className="h-8 w-8 fill-current text-emerald-600"/>}</div><p className="mt-5 text-[10px] font-black uppercase tracking-[.18em] text-emerald-600">It&apos;s a match</p><h2 className="mt-1 text-3xl font-black">You both liked each other</h2><p className="mt-2 text-xs text-zinc-500">Your chat with {match.display_name} is ready.</p><Link href={routes.messages} className="mt-6 flex h-12 items-center justify-center gap-2 rounded-2xl bg-emerald-600 text-xs font-black text-white"><MessageCircle className="h-4 w-4"/>Open chat</Link><button onClick={()=>setMatch(null)} className="mt-3 text-xs font-bold text-zinc-500">Keep discovering</button></motion.div></div>}</AnimatePresence>
  {superChat&&<SuperChatComposer targetUserId={superChat.id} targetName={superChat.display_name??"Member"} onClose={()=>setSuperChat(null)}/>}</main>;
}

function SwipeCard({profile,top,onSwipe,onSafety,onSuperChat}:{profile:DiscoverProfile;top:boolean;onSwipe:(direction:"left"|"right")=>void;onSafety:()=>void;onSuperChat:()=>void}){
 const age=profile.date_of_birth?calculateAge(profile.date_of_birth):null; const photo=profile.profile_photos?.find(p=>p.is_primary)?.url??profile.profile_photo_url; const interests=(profile.profile_interests??[]).flatMap(p=>p.interests?(Array.isArray(p.interests)?p.interests:[p.interests]):[]); const verified=profile.verification_status==="verified"; const areaVerified=profile.area_verification_status==="verified";
 const end=(_:MouseEvent|TouchEvent|PointerEvent,info:PanInfo)=>{if(Math.abs(info.offset.x)>swipeDistance)onSwipe(info.offset.x>0?"right":"left");};
 return <motion.article drag={top?"x":false} dragConstraints={{left:0,right:0}} dragElastic={0.2} onDragEnd={end} animate={top?{x:0,y:0,scale:1}:{scale:.97,y:12}} transition={{type:"spring",stiffness:420,damping:32}} className="absolute inset-0 overflow-hidden rounded-[2rem] border border-zinc-200 bg-white shadow-[0_12px_40px_rgba(24,24,27,.10)]">
  <div className="relative h-[68%] min-h-[300px] bg-zinc-100">{photo?<Image src={photo} alt="" fill priority={top} sizes="(max-width:640px) 100vw,390px" className="object-cover"/>:<div className="grid h-full place-items-center text-5xl font-black text-zinc-300">{profile.display_name?.charAt(0)??"?"}</div>}
   <div className="absolute right-3 top-3 flex max-w-[72%] flex-col items-end gap-1.5"><span className={`inline-flex items-center gap-1 rounded-full border px-2.5 py-1 text-[9px] font-black shadow-sm ${verified?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-rose-200 bg-rose-50 text-rose-700"}`}><ShieldCheck className="h-3 w-3"/>{verified?"Identity verified":"Identity not verified"}</span><span className={`inline-flex items-center gap-1 rounded-full border px-2.5 py-1 text-[9px] font-black shadow-sm ${areaVerified?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-rose-200 bg-rose-50 text-rose-700"}`}><MapPin className="h-3 w-3"/>{areaVerified?`Area verified${profile.area_name?` · ${profile.area_name}`:""}`:"Area not verified"}</span></div>
   <button onClick={onSafety} aria-label="More options" className="absolute left-3 top-3 grid h-9 w-9 place-items-center rounded-full bg-white/95 text-zinc-700 shadow-sm"><MoreVertical className="h-4 w-4"/></button>
   <div className="pointer-events-none absolute inset-x-0 bottom-0 h-28 bg-gradient-to-t from-black/45 to-transparent"/>
  </div>
  <div className="flex h-[32%] flex-col p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="truncate text-2xl font-black tracking-tight">{profile.display_name??"Member"}{age!==null&&<span className="ml-1 font-medium text-zinc-500">{age}</span>}</h2><p className="mt-1 truncate text-[11px] font-semibold text-zinc-500">{profile.identity_context||[profile.department,profile.academic_year,profile.area_name].filter(Boolean).join(" · ")}</p></div><button onClick={onSuperChat} aria-label="Send SuperChat" className="flex h-10 shrink-0 items-center gap-1.5 rounded-full border border-emerald-200 bg-emerald-50 px-3 text-[10px] font-black text-emerald-700"><MessageCircle className="h-4 w-4"/>SuperChat</button></div>{profile.bio&&<p className="mt-3 line-clamp-2 text-xs leading-5 text-zinc-600">{profile.bio}</p>}{interests.length>0&&<div className="mt-auto flex gap-1 overflow-hidden pt-3">{interests.slice(0,4).map(i=><span key={i.id} className="shrink-0 rounded-full bg-zinc-100 px-2.5 py-1 text-[9px] font-bold text-zinc-600">{i.name}</span>)}</div>}</div>
 </motion.article>;
}
