"use client";

import { memo, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import Link from "next/link";
import { motion, useMotionValue, useTransform, AnimatePresence, type PanInfo } from "framer-motion";
import { Heart, X, ShieldCheck, Sparkles, MessageCircle, MoreVertical, Flag, UserX, RotateCcw, SlidersHorizontal, ChevronLeft, ChevronRight, MapPin, UserRound, ArrowRight, Loader2, Users, Star } from "lucide-react";
import { likeProfile, passProfile, rewindLastPass, resetPassedProfiles, blockUser, reportUser, superLikeProfile } from "./actions";
import { routes } from "@/config/routes";
import { Button } from "@/components/ui/button";
import { calculateAge } from "@/lib/utils";
import SuperChatComposer from "@/components/payments/superchat-composer";
import { SHOP_PRODUCTS } from "@/lib/shop";

type Interest={id:string;name:string};type ProfileInterest={interests:Interest|Interest[]|null};type ProfilePhoto={storage_path:string;display_order:number;is_primary:boolean;url?:string|null};
export type DiscoverProfile={id:string;display_name:string|null;date_of_birth:string|null;gender:string|null;department:string|null;academic_year:string|null;bio:string|null;campus_residency?:string|null;relationship_goal?:string|null;zodiac?:string|null;prompt_question?:string|null;prompt_answer?:string|null;profile_photos:ProfilePhoto[]|null;profile_interests:ProfileInterest[]|null;profile_photo_url:string|null;verification_status?:string|null;area_verification_status?:string|null;area_name?:string|null};
type Props={profiles:DiscoverProfile[];isPro?:boolean};

function TrustBadge({ok,label}:{ok:boolean;label:string}){return <span className={`inline-flex items-center gap-1 rounded-full border px-2 py-1 text-[9px] font-black backdrop-blur-md ${ok?"border-emerald-300/40 bg-emerald-500/85 text-white":"border-rose-300/40 bg-rose-500/85 text-white"}`}><ShieldCheck className="h-2.5 w-2.5"/>{label}</span>}
function genderLabel(value:string|null){const g=(value||"").toLowerCase();if(g==="woman"||g==="female")return "Woman";if(g==="man"||g==="male")return "Man";if(g==="non-binary"||g==="nonbinary")return "Non-binary";return "Other"}

export default function DiscoverClient({profiles,isPro=false}:Props){
 const router=useRouter();const [deck,setDeck]=useState(profiles);const [loading,setLoading]=useState(false);const [reviewingPassed,setReviewingPassed]=useState(false);const [toast,setToast]=useState<string|null>(null);const [matchModal,setMatchModal]=useState<{profile:DiscoverProfile;matchId?:string}|null>(null);const [safety,setSafety]=useState<DiscoverProfile|null>(null);const [reportProfile,setReportProfile]=useState<DiscoverProfile|null>(null);const [reportReason,setReportReason]=useState("Inappropriate photo or content");const [reportDetails,setReportDetails]=useState("");const [reporting,setReporting]=useState(false);const [superChatProfile,setSuperChatProfile]=useState<DiscoverProfile|null>(null);
 useEffect(()=>{setDeck(profiles);setReviewingPassed(false)},[profiles]);
 useEffect(()=>{for(const p of deck.slice(1,3)){const url=p.profile_photos?.[0]?.url??p.profile_photo_url;if(url){const img=new window.Image();img.decoding="async";img.src=url}}},[deck]);
 function showToast(message:string){setToast(message);window.setTimeout(()=>setToast(null),2600)}
 async function like(id:string){if(loading)return;const target=deck.find(p=>p.id===id);if(!target)return;setLoading(true);setDeck(d=>d.filter(p=>p.id!==id));try{const r=await likeProfile(id);if(r.error){showToast(r.error);setDeck(d=>[target,...d])}else if(r.matched)setMatchModal({profile:target,matchId:r.matchId})}catch{showToast("Something went wrong. Please try again.");setDeck(d=>[target,...d])}finally{setLoading(false)}}
 async function pass(id:string){if(loading)return;const target=deck.find(p=>p.id===id);if(!target)return;setLoading(true);setDeck(d=>d.filter(p=>p.id!==id));try{const r=await passProfile(id);if(r.error){showToast(r.error);setDeck(d=>[target,...d])}}catch{showToast("Something went wrong. Please try again.");setDeck(d=>[target,...d])}finally{setLoading(false)}}
 async function superLike(id:string){if(loading)return;const target=deck.find(p=>p.id===id);if(!target)return;setLoading(true);setDeck(d=>d.filter(p=>p.id!==id));try{const r=await superLikeProfile(id);if(r.error){showToast(r.error);setDeck(d=>[target,...d])}else showToast(`Super Like sent to ${target.display_name??"this person"}.`)}catch{showToast("Couldn't send Super Like. Please try again.");setDeck(d=>[target,...d])}finally{setLoading(false)}}
 async function rewind(){if(!isPro)return;setLoading(true);try{const r=await rewindLastPass();if(r.error)showToast(r.error);else router.refresh()}finally{setLoading(false)}}
 async function reviewPassed(){if(reviewingPassed)return;setReviewingPassed(true);try{const r=await resetPassedProfiles();if(r.error){showToast(r.error);return}if(!r.count){showToast("No passed profiles to review yet.");return}router.refresh()}catch{showToast("Couldn't bring those profiles back. Please try again.")}finally{setReviewingPassed(false)}}
 async function block(profile:DiscoverProfile){setSafety(null);if(!confirm(`Block ${profile.display_name??"this profile"}? You will no longer see each other.`))return;const r=await blockUser(profile.id);if(r.error){showToast(r.error);return}setDeck(d=>d.filter(p=>p.id!==profile.id));showToast("Profile blocked.")}
 async function report(e:React.FormEvent){e.preventDefault();if(!reportProfile)return;setReporting(true);const r=await reportUser(reportProfile.id,reportReason,reportDetails);setReporting(false);if(r.error){showToast(r.error);return}setDeck(d=>d.filter(p=>p.id!==reportProfile.id));setReportProfile(null);setReportDetails("");showToast("Report submitted and profile removed.")}
 const current=deck[0];const superChatPrice=SHOP_PRODUCTS.superchat.amountPaise/100;
 if(!current&&!matchModal)return <div className="relative mx-auto flex min-h-[calc(100dvh-4.5rem)] w-full max-w-md items-center justify-center overflow-hidden px-4 pb-24 pt-8"><motion.section initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="w-full rounded-[2rem] border border-border bg-card p-6 text-center shadow-[0_18px_55px_-30px_rgba(15,23,42,.35)]"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-pink-50 text-pink-600"><Sparkles className="h-7 w-7"/></div><p className="mt-5 text-[10px] font-black uppercase tracking-[.18em] text-muted-foreground">Discover</p><h2 className="mt-1.5 text-2xl font-black tracking-tight">That&apos;s everyone for now.</h2><p className="mx-auto mt-3 max-w-[285px] text-xs leading-5 text-muted-foreground">New people will appear here as they join. You can also review profiles you previously passed.</p><div className="mt-6 grid gap-2.5"><Button type="button" onClick={()=>void reviewPassed()} disabled={reviewingPassed} className="h-12 w-full justify-between rounded-2xl bg-zinc-950 px-4 text-xs font-black text-white"><span className="flex items-center gap-2.5">{reviewingPassed?<Loader2 className="h-4 w-4 animate-spin"/>:<RotateCcw className="h-4 w-4"/>}{reviewingPassed?"Bringing profiles back…":"Review passed profiles"}</span><ArrowRight className="h-4 w-4"/></Button><Link href={routes.profileSetup} className="flex h-11 items-center justify-center gap-2 rounded-2xl border border-border text-xs font-black"><SlidersHorizontal className="h-3.5 w-3.5"/>Edit discovery preferences</Link></div></motion.section></div>;
 return <div className="relative mx-auto flex min-h-[calc(100dvh-3.5rem)] w-full max-w-md flex-col justify-between px-3 pt-1 pb-20 font-sans"><AnimatePresence>{toast&&<motion.div initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} className="fixed left-1/2 top-16 z-[110] -translate-x-1/2 rounded-2xl border border-pink-200 bg-pink-50 px-4 py-2 text-center text-xs font-bold text-pink-800 shadow-xl">{toast}</motion.div>}</AnimatePresence><div className="relative flex min-h-0 flex-1 w-full items-center justify-center py-1"><div className="relative h-[min(72dvh,520px)] w-full max-w-[390px]">{deck.slice(0,2).map((profile,index)=><DiscoverCard key={profile.id} profile={profile} isTop={index===0} onSwipe={dir=>dir==="right"?void like(profile.id):void pass(profile.id)} onOpenSafety={()=>setSafety(profile)} onSuperChat={()=>setSuperChatProfile(profile)}/>)}</div></div>
 {current&&<div className="z-30 mx-auto flex w-full max-w-[348px] items-end justify-center gap-2 rounded-[2rem] border border-zinc-200 bg-white/95 px-2.5 py-2 shadow-[0_12px_35px_rgba(15,23,42,.10)] backdrop-blur-xl"><button type="button" onClick={()=>void rewind()} disabled={!isPro||loading} className="group flex h-14 w-14 shrink-0 flex-col items-center justify-center gap-0.5 rounded-full border border-zinc-200 bg-white text-zinc-500 shadow-sm transition-all active:scale-90 disabled:opacity-35"><RotateCcw className="h-4.5 w-4.5"/><span className="text-[8px] font-bold">Undo</span></button><button type="button" disabled={loading} onClick={()=>void like(current.id)} className="group flex h-14 w-14 shrink-0 flex-col items-center justify-center gap-0.5 rounded-full bg-pink-500 text-white shadow-md shadow-pink-500/25 transition-all active:scale-90 disabled:opacity-50"><Heart className="h-4.5 w-4.5 fill-current"/><span className="text-[8px] font-black">Like</span></button><button type="button" disabled={loading} onClick={()=>void superLike(current.id)} className="group flex h-14 w-14 shrink-0 flex-col items-center justify-center gap-0.5 rounded-full border border-orange-200 bg-white text-orange-500 shadow-sm transition-all active:scale-90 disabled:opacity-50"><Star className="h-4.5 w-4.5 fill-current"/><span className="text-[8px] font-black">Super</span></button><button type="button" disabled={loading} onClick={()=>setSuperChatProfile(current)} className="group flex h-14 w-14 shrink-0 flex-col items-center justify-center gap-0.5 rounded-full bg-violet-600 text-white shadow-md shadow-violet-600/25 transition-all active:scale-90 disabled:opacity-50"><MessageCircle className="h-4.5 w-4.5"/><span className="text-[8px] font-black">Chat</span></button><Link href={`${routes.profileView}/${current.id}`} className="group flex h-14 w-14 shrink-0 flex-col items-center justify-center gap-0.5 rounded-full border border-zinc-300 bg-white text-zinc-700 shadow-sm active:scale-90"><UserRound className="h-4.5 w-4.5"/><span className="text-[8px] font-black">Profile</span></Link></div>}
 <AnimatePresence>{safety&&<div className="fixed inset-0 z-[10000] flex items-center justify-center bg-black/55 p-3 backdrop-blur-sm"><motion.div initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} className="w-full max-w-sm rounded-[2rem] border border-zinc-200 bg-white p-5 text-zinc-950 shadow-2xl"><div className="flex items-center justify-between border-b border-zinc-200 pb-3"><span className="text-sm font-black">Safety controls</span><button type="button" onClick={()=>setSafety(null)} className="rounded-full border border-zinc-200 p-2"><X className="h-4 w-4"/></button></div><div className="mt-3 grid gap-2.5"><Link href={`${routes.profileView}/${safety.id}`} onClick={()=>setSafety(null)} className="flex items-center gap-3 rounded-2xl border border-zinc-200 p-3.5 text-xs font-bold"><UserRound className="h-4 w-4 text-zinc-500"/>View full profile</Link><button type="button" onClick={()=>{setSafety(null);setReportProfile(safety)}} className="flex items-center gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-3.5 text-xs font-bold text-amber-700"><Flag className="h-4 w-4"/>Report profile</button><button type="button" onClick={()=>void block(safety)} className="flex items-center gap-3 rounded-2xl border border-rose-200 bg-rose-50 p-3.5 text-xs font-bold text-rose-700"><UserX className="h-4 w-4"/>Block user</button></div></motion.div></div>}</AnimatePresence>
 <AnimatePresence>{reportProfile&&<div className="fixed inset-0 z-[10001] flex items-center justify-center bg-black/60 p-3 backdrop-blur-sm"><motion.div initial={{scale:.97,opacity:0}} animate={{scale:1,opacity:1}} className="w-full max-w-md rounded-[2rem] bg-white p-5 shadow-2xl"><div className="flex items-center justify-between"><h3 className="text-base font-black">Report {reportProfile.display_name}</h3><button type="button" onClick={()=>setReportProfile(null)} className="rounded-full border border-zinc-200 p-2"><X className="h-4 w-4"/></button></div><form onSubmit={report} className="mt-4 space-y-3"><select value={reportReason} onChange={e=>setReportReason(e.target.value)} className="w-full rounded-xl border border-zinc-200 p-3 text-xs"><option>Inappropriate photo or content</option><option>Harassment or abusive behavior</option><option>Fake or impersonated profile</option><option>Spam or commercial advertising</option><option>Underage user</option><option>Other safety concern</option></select><textarea value={reportDetails} onChange={e=>setReportDetails(e.target.value)} rows={4} maxLength={500} placeholder="Additional details (optional)" className="w-full resize-none rounded-xl border border-zinc-200 p-3 text-xs"/><div className="flex gap-2"><Button type="button" variant="secondary" onClick={()=>setReportProfile(null)} className="flex-1">Cancel</Button><Button type="submit" disabled={reporting} className="flex-1 bg-rose-600 text-white">{reporting?"Submitting…":"Report & Block"}</Button></div></form></motion.div></div>}</AnimatePresence>
 <AnimatePresence>{matchModal&&<div className="fixed inset-0 z-[10002] flex items-center justify-center bg-black/70 p-4 backdrop-blur-md"><motion.div initial={{scale:.88,opacity:0}} animate={{scale:1,opacity:1}} className="relative w-full max-w-sm rounded-3xl bg-card border border-border p-7 text-center shadow-2xl"><button type="button" onClick={()=>setMatchModal(null)} className="absolute right-4 top-4 rounded-full bg-muted p-2"><X className="h-4 w-4"/></button><div className="mx-auto flex h-20 w-20 items-center justify-center overflow-hidden rounded-3xl bg-pink-50">{matchModal.profile.profile_photo_url?<Image src={matchModal.profile.profile_photo_url} alt="" width={80} height={80} className="h-full w-full object-cover"/>:<Heart className="h-8 w-8 text-pink-500" fill="currentColor"/>}</div><p className="mt-4 text-[10px] font-black uppercase tracking-[.16em] text-pink-500">Mutual connection</p><h2 className="mt-1 text-2xl font-black">It&apos;s a Match</h2><p className="mt-2 text-xs text-muted-foreground">You and <span className="font-bold text-pink-600">{matchModal.profile.display_name}</span> liked each other.</p><Link href={matchModal.matchId?`${routes.messages}/${matchModal.matchId}`:routes.matches} className="mt-5 flex w-full items-center justify-center gap-2 rounded-2xl bg-pink-500 py-3.5 text-xs font-bold text-white"><MessageCircle className="h-4 w-4"/>Send first message</Link><Link href={`${routes.profileView}/${matchModal.profile.id}`} className="mt-2 flex w-full items-center justify-center gap-2 rounded-2xl border border-border py-3 text-xs font-bold"><UserRound className="h-4 w-4"/>View profile</Link><button type="button" onClick={()=>setMatchModal(null)} className="mt-2 w-full py-2 text-xs font-semibold text-muted-foreground">Keep browsing</button></motion.div></div>}</AnimatePresence>
 {superChatProfile&&<SuperChatComposer targetUserId={superChatProfile.id} targetName={superChatProfile.display_name??"this person"} onClose={()=>setSuperChatProfile(null)} onComplete={()=>showToast("SuperChat sent.")}/>}</div>;
}

const DiscoverCard=memo(function DiscoverCard({profile,isTop,onSwipe,onOpenSafety,onSuperChat}:{profile:DiscoverProfile;isTop:boolean;onSwipe:(dir:"left"|"right")=>void;onOpenSafety:()=>void;onSuperChat:()=>void}){
 const x=useMotionValue(0);const rotate=useTransform(x,[-240,240],[-14,14]);const likeOpacity=useTransform(x,[35,100],[0,1]);const passOpacity=useTransform(x,[-100,-35],[1,0]);const [photoIndex,setPhotoIndex]=useState(0);const photos=[...(profile.profile_photos??[])].filter(p=>p.url).sort((a,b)=>Number(b.is_primary)-Number(a.is_primary)||a.display_order-b.display_order).slice(0,6);const age=calculateAge(profile.date_of_birth);const interests=profile.profile_interests?.flatMap(item=>item.interests?(Array.isArray(item.interests)?item.interests:[item.interests]):[])??[];const currentPhoto=photos[photoIndex]?.url??profile.profile_photo_url;const dragEnd=(_e:MouseEvent|TouchEvent|PointerEvent,info:PanInfo)=>{if(Math.abs(info.offset.x)>=85)onSwipe(info.offset.x>0?"right":"left")};const identityVerified=profile.verification_status==="verified";const areaVerified=profile.area_verification_status==="verified";
 return <motion.div style={{x:isTop?x:0,rotate:isTop?rotate:0,transform:"translate3d(0,0,0)",WebkitTransform:"translate3d(0,0,0)",backfaceVisibility:"hidden",WebkitBackfaceVisibility:"hidden",willChange:"transform"}} animate={{scale:isTop?1:.96,y:isTop?0:8,opacity:isTop?1:.65}} transition={{type:"spring",stiffness:400,damping:32}} drag={isTop?"x":false} dragConstraints={{left:0,right:0}} dragElastic={.65} onDragEnd={dragEnd} className={`absolute inset-0 overflow-hidden rounded-[2rem] select-none ${isTop?"z-20 cursor-grab active:cursor-grabbing":"z-10 pointer-events-none"}`}>
 <div className="relative h-full w-full overflow-hidden rounded-[2rem] bg-zinc-950 shadow-2xl">{!isTop?<div className="absolute inset-0 bg-zinc-900"/>:<><div className="absolute inset-0">{currentPhoto?<Image src={currentPhoto} alt={profile.display_name??"Profile"} fill priority decoding="async" className="object-cover" sizes="(max-width:640px) 100vw,420px"/>:<div className="flex h-full items-center justify-center bg-zinc-900 text-zinc-400"><UserRound className="h-16 w-16"/></div>}<div className="absolute inset-0 bg-gradient-to-b from-black/65 via-transparent to-black/95 pointer-events-none"/></div>
 {photos.length>1&&<div className="absolute left-4 right-4 top-3 z-30 flex gap-1.5 pointer-events-none">{photos.map((_,index)=><div key={index} className="h-1 flex-1 overflow-hidden rounded-full bg-white/30"><div className={`h-full rounded-full ${index<=photoIndex?"bg-white":"bg-transparent"}`}/></div>)}</div>}
 {photos.length>1&&<><button type="button" aria-label="Previous photo" onClick={e=>{e.stopPropagation();setPhotoIndex(i=>Math.max(0,i-1))}} className="absolute left-0 top-14 bottom-40 z-20 w-1/2"/><button type="button" aria-label="Next photo" onClick={e=>{e.stopPropagation();setPhotoIndex(i=>Math.min(photos.length-1,i+1))}} className="absolute right-0 top-14 bottom-40 z-20 w-1/2"/></>}
 <motion.div style={{opacity:likeOpacity}} className="absolute left-5 top-16 z-40 rounded-2xl border-2 border-emerald-400 bg-emerald-500/95 px-4 py-1.5 text-xl font-black uppercase tracking-wider text-white">LIKE</motion.div><motion.div style={{opacity:passOpacity}} className="absolute right-5 top-16 z-40 rounded-2xl border-2 border-rose-400 bg-rose-500/95 px-4 py-1.5 text-xl font-black uppercase tracking-wider text-white">PASS</motion.div>
 <div className="absolute right-3.5 top-5 z-40 flex max-w-[70%] flex-wrap justify-end gap-1.5"><TrustBadge ok={identityVerified} label={identityVerified?"Identity verified":"Identity not verified"}/><TrustBadge ok={areaVerified} label={areaVerified?"Area verified":"Area not verified"}/><button type="button" onClick={e=>{e.stopPropagation();onOpenSafety()}} className="flex h-8 w-8 items-center justify-center rounded-full border border-white/15 bg-black/65 text-white shadow-sm" aria-label="Safety controls"><MoreVertical className="h-4 w-4"/></button></div>
 <div className="absolute bottom-3 left-4 right-4 z-30 space-y-1.5"><Link href={`${routes.profileView}/${profile.id}`} className="pointer-events-auto inline-flex max-w-full items-center gap-2 rounded-xl bg-black/35 px-2 py-1 text-white backdrop-blur-sm"><h2 className="text-2xl font-black tracking-tight">{profile.display_name||"Member"}{age!==null&&<span className="font-light text-xl opacity-90">, {age}</span>}</h2><UserRound className="h-4 w-4 shrink-0"/></Link><div className="flex flex-wrap items-center gap-2 text-xs font-medium text-zinc-200"><span className="flex items-center gap-1"><UserRound className="h-3 w-3"/>{genderLabel(profile.gender)}</span>{profile.area_name&&<span className="flex items-center gap-1"><MapPin className="h-3 w-3"/>{profile.area_name}</span>}{profile.academic_year&&<span>• {profile.academic_year}</span>}</div><div className="flex flex-wrap gap-1.5">{profile.area_name&&<span className="rounded-full bg-white/15 px-2 py-1 text-[9px] font-bold text-white">{profile.area_name}</span>}<span className="rounded-full bg-white/15 px-2 py-1 text-[9px] font-bold text-white">{identityVerified?"Identity trusted":"Identity pending"}</span></div>{profile.prompt_question&&profile.prompt_answer?<div className="rounded-xl border border-white/10 bg-black/50 p-2 backdrop-blur-md"><span className="mb-0.5 block text-[10px] font-bold text-pink-300">{profile.prompt_question}</span><p className="line-clamp-2 text-xs text-white/95">&ldquo;{profile.prompt_answer}&rdquo;</p></div>:profile.bio?<p className="line-clamp-2 text-xs text-white/90">&ldquo;{profile.bio}&rdquo;</p>:null}<div className="flex flex-wrap gap-1">{profile.relationship_goal&&<span className="rounded-full bg-pink-500/80 px-2.5 py-0.5 text-[9px] font-bold text-white">{profile.relationship_goal}</span>}{profile.zodiac&&<span className="rounded-full bg-purple-500/80 px-2.5 py-0.5 text-[9px] font-bold text-white">{profile.zodiac}</span>}{interests.slice(0,3).map(i=><span key={i.id} className="rounded-full border border-white/15 bg-white/15 px-2 py-0.5 text-[9px] font-medium text-white">{i.name}</span>)}</div><div className="pointer-events-auto flex items-center justify-between gap-2 border-t border-white/15 pt-2"><span className="text-[9px] font-semibold text-white/55">← Pass</span><button type="button" onClick={e=>{e.stopPropagation();onSuperChat()}} className="inline-flex items-center gap-1.5 rounded-full border border-violet-300/40 bg-violet-600 px-3 py-1.5 text-[10px] font-black text-white shadow-lg"><MessageCircle className="h-3.5 w-3.5"/>SuperChat · ₹{SHOP_PRODUCTS.superchat.amountPaise/100}</button><span className="text-[9px] font-semibold text-white/55">Like →</span></div></div></>}</div></motion.div>;
});
