"use client";
import {FormEvent,useState} from "react"; import Link from "next/link"; import {ArrowLeft,CheckCircle2,FileCheck2,MessageCircle,Send,ShieldCheck} from "lucide-react"; import {routes} from "@/config/routes";
type Message={id:number;role:"bot"|"user";text:string};
const quick=["How does verification work?","How do I report someone?","How do I delete my account?","I have a payment problem"];
function reply(input:string){const t=input.toLowerCase();if(/verif|identity|selfie|area/.test(t))return"Verification is optional. Identity verification can add a verified badge, while area verification confirms your selected Extrovert area. Your documents and selfies are private.";if(/report|block|harass|abuse|unsafe|scam/.test(t))return"Open the profile menu to report or block someone. Reporting also removes that profile from your current discovery view. If you feel unsafe, stop engaging and contact the team.";if(/delete|remove account|close account/.test(t))return"You can permanently delete your account from Settings. Take a moment to make sure you want to remove your profile and data before confirming.";if(/pay|payment|subscription|refund|razorpay/.test(t))return"For payment issues, use Contact & Feedback and include the charge context. Never send an OTP, UPI PIN, password or card number.";if(/match|like|dating/.test(t))return"In Discover, swipe right to like and left to pass. A mutual like becomes a match and opens chat.";if(/social|connect|friend/.test(t))return"Explore is the social side. Pick Waknaghat, Solan or Shimla, open a local profile and send a connection request. Accepted connections can chat.";return"I can help with verification, Discover, Explore, safety, payments, login and account settings. For something specific, contact the Extrovert team."}
export default function SupportPage(){const[messages,setMessages]=useState<Message[]>([{id:1,role:"bot",text:"Welcome to Extrovert Support. Ask me anything about the app."}]);const[input,setInput]=useState("");function send(value:string){const v=value.trim();if(!v)return;setMessages(m=>[...m,{id:m.length+1,role:"user",text:v},{id:m.length+2,role:"bot",text:reply(v)}]);setInput("")}function submit(e:FormEvent){e.preventDefault();send(input)}return <main className="mx-auto flex min-h-[calc(100dvh-4rem)] w-full max-w-2xl flex-col px-3.5 pb-24 pt-5 font-sans sm:px-5">
 <header className="flex items-center justify-between"><Link href={routes.settings} className="inline-flex items-center gap-1 text-[10px] font-bold text-zinc-500 hover:text-emerald-700"><ArrowLeft className="h-3.5 w-3.5"/>Settings</Link><span className="inline-flex items-center gap-1 rounded-full border border-emerald-100 bg-emerald-50 px-2.5 py-1 text-[9px] font-black text-emerald-700"><ShieldCheck className="h-3 w-3"/>Private support</span></header>
 <section className="mt-5 rounded-[1.75rem] border border-emerald-100 bg-emerald-50/60 p-5 shadow-sm"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-white text-emerald-600 shadow-sm"><MessageCircle className="h-5 w-5"/></div><div><p className="text-[9px] font-black uppercase tracking-[.16em] text-emerald-700">EXTROVERT SUPPORT</p><h1 className="text-2xl font-black tracking-tight text-emerald-950">Help without the runaround.</h1></div></div><p className="mt-3 max-w-xl text-xs leading-5 text-emerald-900/70">Fast answers for common issues. No external AI service is required for this support layer.</p></section>
 <section className="mt-3 rounded-[1.75rem] border border-zinc-200 bg-white p-4 shadow-sm"><div className="flex items-start gap-3"><FileCheck2 className="mt-0.5 h-5 w-5 shrink-0 text-emerald-600"/><div><p className="text-xs font-black">Built by a registered Indian micro enterprise</p><p className="mt-1 text-[10px] leading-4 text-zinc-500">We publish a public-safe copy of the Extrovert Udyam registration certificate for transparency. Personal fields are kept out of the UI.</p><a href="/trust/extrovert-udyam-registration.pdf" target="_blank" rel="noreferrer" className="mt-2 inline-flex items-center gap-1 text-[10px] font-black text-emerald-700">View certificate <CheckCircle2 className="h-3.5 w-3.5"/></a></div></div></section>
 <div className="mt-3 flex flex-wrap gap-1.5">{quick.map(q=><button key={q} onClick={()=>send(q)} className="rounded-full border border-zinc-200 bg-white px-3 py-2 text-[10px] font-bold shadow-sm hover:border-emerald-200 hover:bg-emerald-50/40">{q}</button>)}</div>
 <section className="mt-3 flex-1 space-y-2 overflow-y-auto rounded-[1.75rem] border border-zinc-200 bg-zinc-50/70 p-3 shadow-sm">{messages.map(m=><div key={m.id} className={`flex ${m.role==="user"?"justify-end":"justify-start"}`}><div className={`max-w-[88%] rounded-2xl px-3 py-2.5 text-[11px] leading-5 ${m.role==="user"?"rounded-br-md bg-emerald-600 text-white":"rounded-bl-md border border-zinc-200 bg-white text-zinc-800 shadow-sm"}`}>{m.text}</div></div>)}</section>
 <form onSubmit={submit} className="mt-3 flex items-center gap-2 rounded-2xl border border-zinc-200 bg-white p-2 shadow-sm"><MessageCircle className="ml-1 h-4 w-4 text-zinc-400"/><input value={input} onChange={e=>setInput(e.target.value)} maxLength={1000} className="min-w-0 flex-1 bg-transparent px-1 py-2 text-xs outline-none" placeholder="Ask support something..."/><button type="submit" disabled={!input.trim()} className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-600 text-white shadow-sm disabled:cursor-wait disabled:opacity-40" aria-label="Send"><Send className="h-4 w-4"/></button></form>
 <Link href={routes.feedback} className="mt-2 text-center text-[10px] font-black text-emerald-700">Need a human? Contact the Extrovert team →</Link>
 </main>}
