"use client";

import Link from "next/link";
import { ArrowLeft, Compass, Heart } from "lucide-react";
import { routes } from "@/config/routes";

export default function NotFound() {
  return <main className="relative flex min-h-[100dvh] items-center justify-center overflow-hidden bg-[#fffdfb] px-4 py-8 text-zinc-950 antialiased"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top,_rgba(118,31,48,0.10),_transparent_45%)]" aria-hidden="true"/><section className="relative z-10 w-full max-w-md rounded-[30px] border border-[#e5cbd0] bg-white p-7 text-center shadow-[0_20px_60px_rgba(118,31,48,.10)]"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-[#faf0f2] text-[#761f30]"><Heart className="h-6 w-6 fill-current"/></div><p className="mt-5 inline-flex rounded-full border border-[#e5cbd0] bg-[#faf0f2] px-3 py-1 text-[10px] font-black uppercase tracking-widest text-[#761f30]">Error 404</p><h1 className="mt-3 text-3xl font-black tracking-tight">Looks like you wandered off.</h1><p className="mx-auto mt-2 max-w-xs text-sm leading-6 text-zinc-500">This page doesn&apos;t exist in Extrovert. Head back and keep discovering.</p><div className="mt-6 grid gap-2.5"><Link href={routes.home} className="inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-[#761f30] px-4 py-3.5 text-xs font-black text-white shadow-sm transition hover:bg-[#5b1423] active:scale-[.99]"><Compass className="h-4 w-4"/>Back to Extrovert</Link><button onClick={()=>window.history.back()} className="inline-flex w-full cursor-pointer items-center justify-center gap-2 rounded-2xl border border-zinc-200 bg-white px-4 py-3 text-xs font-bold text-zinc-600 transition-colors hover:bg-zinc-50 hover:text-zinc-950 active:scale-[.99]"><ArrowLeft className="h-4 w-4"/>Go back</button></div></section><p className="absolute bottom-4 text-[10px] font-medium text-zinc-400">Extrovert · Dating, reimagined</p></main>;
}
