import Link from "next/link";
import { ArrowRight, Heart, MapPin, ShieldCheck, Users, LockKeyhole, MessageCircle } from "lucide-react";
import { routes } from "@/config/routes";

export default function HomePage() {
  return <main className="min-h-[100dvh] bg-white text-zinc-950"><div className="mx-auto w-full max-w-[900px] px-4 pb-16 pt-5 sm:px-8 sm:pt-10"><header className="flex items-center justify-between"><div className="flex items-center gap-2.5"><div className="grid size-10 place-items-center rounded-2xl bg-zinc-950 text-emerald-400 shadow-sm"><Heart size={18} fill="currentColor"/></div><div><p className="text-[10px] font-black tracking-[.18em] text-emerald-600">EXTROVERT</p><p className="text-sm font-black">Dating + social</p></div></div><Link href={routes.login} className="pressable smooth rounded-full border border-zinc-200 bg-white px-4 py-2 text-xs font-black">Sign in</Link></header>
    <section className="mt-8 overflow-hidden rounded-[34px] bg-zinc-950 px-6 py-10 text-white shadow-[0_30px_90px_-45px_rgba(15,23,42,.5)] sm:px-10 sm:py-14"><div className="max-w-2xl"><span className="inline-flex items-center gap-1.5 rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.16em] text-emerald-300"><Heart size={12} fill="currentColor"/> One place to meet people</span><h1 className="mt-5 text-[clamp(3rem,9vw,5.8rem)] font-black leading-[.9] tracking-[-.065em]">Meet someone<br/><span className="text-emerald-400">worth talking to.</span></h1><p className="mt-6 max-w-xl text-sm leading-6 text-zinc-300 sm:text-base">Extrovert brings dating and social discovery together. Date when you want to date, connect socially when you don't, or use both. One account. One profile. No phone number required.</p><Link href={routes.login} className="pressable smooth mt-7 inline-flex h-12 items-center gap-2 rounded-2xl bg-emerald-500 px-5 text-sm font-black text-white shadow-lg shadow-emerald-950/30">Continue with Google <ArrowRight size={16}/></Link></div></section>
    <section className="mt-5 grid gap-3 sm:grid-cols-4"><article className="rounded-3xl border border-zinc-200 bg-white p-5 shadow-sm"><ShieldCheck className="h-5 w-5 text-emerald-600"/><h2 className="mt-4 text-sm font-black">Trust by choice</h2><p className="mt-1 text-xs leading-5 text-zinc-500">Identity verification is optional and can be completed later.</p></article><article className="rounded-3xl border border-zinc-200 bg-white p-5 shadow-sm"><MapPin className="h-5 w-5 text-emerald-600"/><h2 className="mt-4 text-sm font-black">Local discovery</h2><p className="mt-1 text-xs leading-5 text-zinc-500">Waknaghat, Solan and Shimla, without exposing exact coordinates.</p></article><article className="rounded-3xl border border-zinc-200 bg-white p-5 shadow-sm"><Users className="h-5 w-5 text-emerald-600"/><h2 className="mt-4 text-sm font-black">Dating or social</h2><p className="mt-1 text-xs leading-5 text-zinc-500">Choose dating, social, or both from the same profile.</p></article><article className="rounded-3xl border border-zinc-200 bg-white p-5 shadow-sm"><MessageCircle className="h-5 w-5 text-emerald-600"/><h2 className="mt-4 text-sm font-black">Real conversations</h2><p className="mt-1 text-xs leading-5 text-zinc-500">Likes become matches, matches become conversations.</p></article></section>
    <section className="mt-5 rounded-3xl border border-emerald-100 bg-emerald-50/70 p-5 sm:p-7"><div className="flex items-start gap-3"><LockKeyhole className="mt-0.5 h-5 w-5 shrink-0 text-emerald-600"/><div><p className="text-xs font-black">Verification stays private</p><p className="mt-1 text-[11px] leading-5 text-zinc-600">Identity documents and selfies are never shown to other users. Profiles only show clear verification results such as Identity Verified and Area Verified.</p></div></div></section>
    <footer className="mt-10 border-t border-zinc-200 pt-5 text-[10px] leading-5 text-zinc-500"><p className="font-bold text-zinc-800">Extrovert</p><p className="mt-1">One standalone app for dating and social connection. Your exact location and verification documents stay private.</p></footer>
  </div></main>;
}
