import Link from "next/link";
import { ArrowRight, Heart, MapPin, ShieldCheck, Sparkles, Users, LockKeyhole } from "lucide-react";
import { routes } from "@/config/routes";

export default function HomePage() {
  return <main className="min-h-[100dvh] bg-white text-zinc-950"><div className="mx-auto w-full max-w-[900px] px-4 pb-16 pt-5 sm:px-8 sm:pt-10"><header className="flex items-center justify-between"><div className="flex items-center gap-2.5"><div className="grid size-10 place-items-center rounded-2xl bg-zinc-950 text-emerald-400 shadow-sm"><Heart size={18} fill="currentColor"/></div><div><p className="text-[10px] font-black tracking-[.18em] text-emerald-600">EXTROVERT DATE</p><p className="text-sm font-black">Local dating</p></div></div><Link href={routes.login} className="pressable smooth rounded-full border border-zinc-200 bg-white px-4 py-2 text-xs font-black">Sign in</Link></header>
    <section className="mt-8 overflow-hidden rounded-[34px] bg-zinc-950 px-6 py-10 text-white shadow-[0_30px_90px_-45px_rgba(15,23,42,.5)] sm:px-10 sm:py-14"><div className="max-w-2xl"><span className="inline-flex items-center gap-1.5 rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.16em] text-emerald-300"><Sparkles size={12}/> Dating on your terms</span><h1 className="mt-5 text-[clamp(3rem,9vw,5.8rem)] font-black leading-[.9] tracking-[-.065em]">Meet someone<br/><span className="text-emerald-400">worth talking to.</span></h1><p className="mt-6 max-w-xl text-sm leading-6 text-zinc-300 sm:text-base">Extrovert Date is the dating side of Extrovert. Your name, gender, local area and verification stay connected to one identity, so people know who they are talking to.</p><Link href={routes.login} className="pressable smooth mt-7 inline-flex h-12 items-center gap-2 rounded-2xl bg-emerald-500 px-5 text-sm font-black text-white shadow-lg shadow-emerald-950/30">Start dating <ArrowRight size={16}/></Link></div></section>
    <section className="mt-5 grid gap-3 sm:grid-cols-3"><article className="rounded-3xl border border-zinc-200 bg-white p-5 shadow-sm"><ShieldCheck className="h-5 w-5 text-emerald-600"/><h2 className="mt-4 text-sm font-black">Trust first</h2><p className="mt-1 text-xs leading-5 text-zinc-500">Identity and area verification are visible as clear trust signals.</p></article><article className="rounded-3xl border border-zinc-200 bg-white p-5 shadow-sm"><MapPin className="h-5 w-5 text-emerald-600"/><h2 className="mt-4 text-sm font-black">Local discovery</h2><p className="mt-1 text-xs leading-5 text-zinc-500">Find people around your selected area without exposing exact coordinates.</p></article><article className="rounded-3xl border border-zinc-200 bg-white p-5 shadow-sm"><Users className="h-5 w-5 text-emerald-600"/><h2 className="mt-4 text-sm font-black">Real conversations</h2><p className="mt-1 text-xs leading-5 text-zinc-500">Likes become matches, matches become conversations and dates happen when you choose.</p></article></section>
    <section className="mt-5 rounded-3xl border border-emerald-100 bg-emerald-50/70 p-5 sm:p-7"><p className="text-[10px] font-black uppercase tracking-[.16em] text-emerald-700">One identity · two experiences</p><div className="mt-3 flex flex-col gap-3 sm:flex-row sm:items-center"><div className="flex-1 rounded-2xl bg-white p-4"><p className="text-sm font-black">Extrovert Social</p><p className="mt-1 text-xs text-zinc-500">People, friends, connections and social chat.</p></div><ArrowRight className="mx-auto hidden text-emerald-600 sm:block" size={18}/><div className="flex-1 rounded-2xl bg-zinc-950 p-4 text-white"><p className="text-sm font-black">Extrovert Date</p><p className="mt-1 text-xs text-zinc-400">Dating, likes, matches and encrypted dating chat.</p></div></div></section>
    <section className="mt-5 flex items-center gap-3 rounded-3xl border border-zinc-200 bg-white p-5 shadow-sm"><LockKeyhole className="h-5 w-5 shrink-0 text-emerald-600"/><div><p className="text-xs font-black">Private conversations</p><p className="mt-1 text-[11px] leading-5 text-zinc-500">New dating messages are encrypted in your browser before they leave your device.</p></div></section>
    <footer className="mt-10 border-t border-zinc-200 pt-5 text-[10px] leading-5 text-zinc-500"><p className="font-bold text-zinc-800">Extrovert Date</p><p className="mt-1">Dating information stays in Date. Shared identity and trust information stay managed by Extrovert.</p></footer>
  </div></main>;
}
