import Link from "next/link";
import { ArrowRight, Heart, ShieldCheck, Users, Link2, LockKeyhole } from "lucide-react";

const PRODUCTION_DATELOCAL_URL = "https://datelocal-gaurav-7489s-projects.vercel.app";
const PRODUCTION_EXTROVERT_URL = "https://extrovert-ten.vercel.app";
const LOCAL_HOSTS = new Set(["localhost", "127.0.0.1"]);
function normalizeOrigin(value: string | undefined) { if (!value) return null; try { return new URL(value.trim()).origin; } catch { return null; } }
function getAppOrigin() { const configured=normalizeOrigin(process.env.NEXT_PUBLIC_APP_URL); if(process.env.NODE_ENV==="production") return configured&&!LOCAL_HOSTS.has(new URL(configured).hostname)?configured:PRODUCTION_DATELOCAL_URL; return configured??"http://localhost:3001"; }
function getExtrovertOrigin(appOrigin:string) { const configured=(process.env.EXTROVERT_URL??"").split(",").map(normalizeOrigin).filter((v):v is string=>Boolean(v)); const local=LOCAL_HOSTS.has(new URL(appOrigin).hostname); if(process.env.NODE_ENV==="production") return configured.find(v=>!LOCAL_HOSTS.has(new URL(v).hostname))??PRODUCTION_EXTROVERT_URL; return configured.find(v=>LOCAL_HOSTS.has(new URL(v).hostname))??configured[0]??(local?"http://localhost:3000":PRODUCTION_EXTROVERT_URL); }

export default function LoginPage() {
  const appOrigin=getAppOrigin(); const extrovert=getExtrovertOrigin(appOrigin); const returnTo=`${appOrigin}/auth/callback`; const handoffUrl=`${extrovert}/auth/datelocal?returnTo=${encodeURIComponent(returnTo)}`;
  return <main className="min-h-[100dvh] bg-white px-5 py-8 font-sans text-zinc-950"><div className="mx-auto flex min-h-[calc(100dvh-4rem)] w-full max-w-md flex-col justify-center"><div className="mb-8"><div className="mb-4 grid size-12 place-items-center rounded-2xl bg-zinc-950 text-emerald-400 shadow-sm"><Heart size={22} fill="currentColor"/></div><p className="text-[10px] font-black uppercase tracking-[.18em] text-emerald-600">EXTROVERT DATE · DATING APP</p><h1 className="mt-2 text-4xl font-black tracking-[-.055em]">Dating starts local.</h1><p className="mt-3 max-w-sm text-sm leading-6 text-zinc-500">This is the dating side of Extrovert — for profiles, likes, matches and private dating conversations.</p></div><section className="space-y-2.5"><div className="flex items-center gap-3 rounded-2xl border border-zinc-200 bg-white p-3.5 shadow-xs"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-emerald-50 text-emerald-600"><ShieldCheck className="h-5 w-5"/></div><div><p className="text-xs font-black">One verified identity</p><p className="mt-0.5 text-[11px] leading-4 text-zinc-500">Extrovert owns your identity, gender and trust signals.</p></div></div><div className="flex items-center gap-3 rounded-2xl border border-zinc-200 bg-white p-3.5 shadow-xs"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-emerald-50 text-emerald-600"><Heart className="h-5 w-5"/></div><div><p className="text-xs font-black">Dating lives here</p><p className="mt-0.5 text-[11px] leading-4 text-zinc-500">Discovery, preferences, likes, matches and dating chat.</p></div></div><div className="flex items-center gap-3 rounded-2xl border border-zinc-200 bg-white p-3.5 shadow-xs"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-emerald-50 text-emerald-600"><LockKeyhole className="h-5 w-5"/></div><div><p className="text-xs font-black">Private by design</p><p className="mt-0.5 text-[11px] leading-4 text-zinc-500">New dating messages are encrypted before they leave your browser.</p></div></div></section><a href={handoffUrl} className="mt-6 flex h-13 w-full items-center justify-between rounded-2xl bg-emerald-600 px-5 text-sm font-black text-white shadow-lg shadow-emerald-900/10 transition-transform active:scale-[.99]"><span>Continue with Extrovert</span><ArrowRight className="h-4 w-4"/></a><div className="mt-5 flex items-center justify-center gap-2 text-[10px] font-semibold text-zinc-500"><Link2 className="h-3.5 w-3.5 text-emerald-600"/><span>One Extrovert identity · two focused apps</span></div><div className="mt-3 flex items-center justify-center gap-4 text-[10px] text-zinc-400"><Link href="/safety">Safety</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><span className="inline-flex items-center gap-1"><Users className="h-3 w-3"/>Campus dating</span></div></div></main>;
}
