import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, Flag, CheckCircle2 } from "lucide-react";
import { requireAdmin } from "@/lib/auth/admin";
import { createAdminClient } from "@/lib/supabase/admin";
import { routes } from "@/config/routes";
import { updateReportStatus } from "../actions";

export const metadata:Metadata={title:"Reports | DateLocal Admin",robots:{index:false,follow:false}};
export const dynamic="force-dynamic";

export default async function ReportsPage(){
 await requireAdmin(); const db=createAdminClient();
 const {data:reports}=await db.from("reports").select("id,reporter_id,reported_id,reason,details,status,created_at,reviewed_by,reviewed_at,admin_note").order("created_at",{ascending:false}).limit(100);
 return <main className="min-h-screen bg-zinc-50 font-sans text-zinc-950"><header className="sticky top-0 z-20 border-b border-zinc-200 bg-white/95"><div className="mx-auto flex h-14 max-w-5xl items-center gap-3 px-4 sm:px-6"><Link href={routes.admin.root} className="grid h-8 w-8 place-items-center rounded-lg border border-zinc-200 text-zinc-500"><ArrowLeft className="h-4 w-4"/></Link><div><p className="text-[9px] font-black uppercase tracking-[.16em] text-emerald-600">DateLocal · Safety</p><h1 className="text-sm font-black">All Reports</h1></div></div></header><div className="mx-auto max-w-5xl space-y-3 px-4 py-6 sm:px-6"><div className="rounded-3xl border border-zinc-200 bg-white p-4 shadow-xs"><p className="text-xs font-black">Moderation record</p><p className="mt-1 text-[9px] leading-5 text-zinc-500">IDs, reasons, details and status are visible to authorized admins. Encrypted chat content is not exposed.</p></div>{(reports??[]).length===0?<div className="rounded-3xl border border-zinc-200 bg-white p-10 text-center"><CheckCircle2 className="mx-auto h-7 w-7 text-emerald-500"/><p className="mt-2 text-xs font-black">No reports yet</p></div>:(reports??[]).map(r=><article key={r.id} className="rounded-3xl border border-zinc-200 bg-white p-4 shadow-xs"><div className="flex flex-wrap items-center gap-2"><Flag className="h-4 w-4 text-amber-600"/><span className="rounded-full bg-zinc-100 px-2 py-0.5 text-[8px] font-bold text-zinc-600">{r.status}</span><span className="text-[9px] font-black">{r.reason}</span><span className="text-[8px] text-zinc-400">{new Date(r.created_at).toLocaleString("en-IN")}</span></div><div className="mt-3 grid gap-2 text-[9px] sm:grid-cols-2"><p className="break-all"><b>Report ID</b> · {r.id}</p><p className="break-all"><b>Reporter ID</b> · {r.reporter_id}</p><p className="break-all"><b>Reported ID</b> · {r.reported_id}</p><p className="break-all"><b>Reviewed by</b> · {r.reviewed_by??"Not reviewed"}</p></div>{r.details&&<div className="mt-3 rounded-2xl bg-zinc-50 p-3 text-[10px] leading-5">{r.details}</div>}<form action={updateReportStatus} className="mt-3 flex flex-wrap items-center gap-1.5"><input type="hidden" name="reportId" value={r.id}/><input type="text" name="adminNote" defaultValue={r.admin_note??""} placeholder="Internal note" className="min-w-48 flex-1 rounded-xl border border-zinc-200 px-3 py-2 text-[9px] outline-none focus:border-emerald-500"/>{["reviewed","resolved","dismissed","pending"].map(s=><button key={s} name="status" value={s} className="rounded-xl border border-zinc-200 bg-white px-3 py-2 text-[9px] font-bold hover:bg-zinc-50">{s}</button>)}</form></article>)}</div></main>;
}
