"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { Lock, Mail, CheckCircle2, AlertCircle } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { sendPasswordResetEmail } from "@/services/auth.service";
import { routes } from "@/config/routes";
export default function ResetPasswordClient() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [sent, setSent] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [updating, setUpdating] = useState(false); const [recoveryReady, setRecoveryReady] = useState(false);
  useEffect(() => { void createClient().auth.getSession().then(({ data }) => { setRecoveryReady(Boolean(data.session)); }); }, []);
  async function requestReset(event: FormEvent) { event.preventDefault(); setError(""); const result = await sendPasswordResetEmail(email); if (!result.success) { setError(result.error); return; } setSent(true); }
  async function updatePassword(event: FormEvent) { event.preventDefault(); setError(""); if (password.length < 8) { setError("Your new password must be at least 8 characters long."); return; } setUpdating(true); const { error: updateError } = await createClient().auth.updateUser({ password }); setUpdating(false); if (updateError) { setError(`We couldn't update your password: ${updateError.message}`); return; } setMessage("Password updated. You can now sign in with your new password."); }
  return <main className="mx-auto flex min-h-[80dvh] max-w-md items-center px-4 py-10"><div className="w-full rounded-3xl border border-border bg-card p-6 shadow-sm"><h1 className="text-2xl font-black text-foreground">Reset your password</h1><p className="mt-2 text-sm text-muted-foreground">Enter your account email and we&apos;ll send a secure reset link.</p>{recoveryReady?<div className="mt-6 space-y-4"><div className="flex gap-2 rounded-2xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700"><CheckCircle2 className="h-5 w-5 shrink-0"/>Check your inbox for the reset link. It may take a minute to arrive.</div><form onSubmit={updatePassword} className="space-y-3"><label className="block text-sm font-semibold">New password</label><input className="w-full rounded-xl border border-border bg-background px-3 py-2" type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 8 characters"/><button className="w-full rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-60" disabled={updating}>{updating?"Updating...":"Set new password"}</button></form></div>:sent?<div className="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700"><CheckCircle2 className="mr-2 inline h-5 w-5"/>Reset email sent. Open the link in your inbox to choose a new password.</div>:<form onSubmit={requestReset} className="mt-6 space-y-3"><label className="flex items-center gap-2 text-sm font-semibold"><Mail className="h-4 w-4"/> Account email</label><input className="w-full rounded-xl border border-border bg-background px-3 py-2" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/><button className="w-full rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white">Email me a reset link</button></form>}{(error||message)&&<div className={`mt-4 flex gap-2 rounded-xl p-3 text-sm ${error?"bg-rose-50 text-rose-700":"bg-emerald-50 text-emerald-700"}`}><AlertCircle className="h-4 w-4 shrink-0"/>{error||message}</div>}<Link className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-emerald-700" href={routes.login}><Lock className="h-4 w-4"/> Back to login</Link></div></main>;
}
