create table if not exists public.extrovert_token_wallets (user_id uuid primary key references auth.users(id) on delete cascade, balance integer not null default 0 check(balance>=0), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.extrovert_token_ledger (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, amount integer not null, reason text not null, source_superlike_id uuid unique, created_at timestamptz not null default now());
alter table public.extrovert_token_wallets enable row level security; alter table public.extrovert_token_ledger enable row level security;
drop policy if exists token_wallet_select_own on public.extrovert_token_wallets; create policy token_wallet_select_own on public.extrovert_token_wallets for select using(user_id=auth.uid());
drop policy if exists token_ledger_select_own on public.extrovert_token_ledger; create policy token_ledger_select_own on public.extrovert_token_ledger for select using(user_id=auth.uid());

create or replace function public.is_datebu_pro() returns boolean language sql stable security definer set search_path=public as $function$
select exists(select 1 from public.extrovert_profiles e where e.id=auth.uid() and e.gender='woman') or exists(select 1 from public.subscriptions s where s.user_id=auth.uid() and s.plan='pro' and s.status in ('trialing','active') and ((s.status='trialing' and s.trial_ends_at>now()) or (s.status='active' and s.current_period_end>now())));
$function$;

create or replace function public.get_like_status() returns table(starter_remaining integer,daily_used integer,daily_limit integer,purchased_remaining integer,is_pro boolean) language sql stable security definer set search_path=public as $function$
select p.starter_likes_remaining,case when p.daily_likes_date=timezone('Asia/Kolkata',now())::date then p.daily_likes_used else 0 end,case when exists(select 1 from public.extrovert_profiles e where e.id=auth.uid() and e.gender='woman') then 2147483647 when public.is_datebu_pro() then 10 else 2 end,coalesce(lw.purchased_likes,0),public.is_datebu_pro() from public.profiles p left join public.like_wallets lw on lw.user_id=p.id where p.id=auth.uid();
$function$;

create or replace function public.like_profile(p_profile_id uuid) returns table(matched boolean,match_id uuid) language plpgsql security definer set search_path=public as $function$
declare v_user_id uuid:=auth.uid();v_user_a uuid;v_user_b uuid;v_match_id uuid;v_is_pro boolean:=public.is_datebu_pro();v_is_woman boolean:=exists(select 1 from public.extrovert_profiles e where e.id=v_user_id and e.gender='woman');v_today date:=timezone('Asia/Kolkata',now())::date;v_starter integer;v_daily integer;v_purchased integer;
begin if v_user_id is null then raise exception 'AUTH_REQUIRED';end if;if v_user_id=p_profile_id then raise exception 'INVALID_PROFILE';end if;if not exists(select 1 from public.profiles p where p.id=p_profile_id and p.profile_completed=true and p.ghost_mode=false) then raise exception 'PROFILE_UNAVAILABLE';end if;if exists(select 1 from public.blocks b where (b.blocker_id=v_user_id and b.blocked_id=p_profile_id) or (b.blocker_id=p_profile_id and b.blocked_id=v_user_id)) then raise exception 'USER_UNAVAILABLE';end if;
insert into public.like_wallets(user_id) values(v_user_id) on conflict(user_id) do nothing;select starter_likes_remaining,daily_likes_used into v_starter,v_daily from public.profiles where id=v_user_id for update;select purchased_likes into v_purchased from public.like_wallets where user_id=v_user_id for update;update public.profiles set daily_likes_used=0,daily_likes_date=v_today where id=v_user_id and daily_likes_date<>v_today;select daily_likes_used,starter_likes_remaining into v_daily,v_starter from public.profiles where id=v_user_id;
if not v_is_woman then if v_is_pro then if v_daily<10 then update public.profiles set daily_likes_used=daily_likes_used+1 where id=v_user_id;elsif v_purchased>0 then update public.like_wallets set purchased_likes=purchased_likes-1,updated_at=now() where user_id=v_user_id;else raise exception 'LIKE_LIMIT_REACHED';end if;elsif v_starter>0 then update public.profiles set starter_likes_remaining=starter_likes_remaining-1 where id=v_user_id;elsif v_daily<2 then update public.profiles set daily_likes_used=daily_likes_used+1 where id=v_user_id;elsif v_purchased>0 then update public.like_wallets set purchased_likes=purchased_likes-1,updated_at=now() where user_id=v_user_id;else raise exception 'LIKE_LIMIT_REACHED';end if;end if;
insert into public.likes(liker_id,liked_id) values(v_user_id,p_profile_id) on conflict(liker_id,liked_id) do nothing;v_user_a:=least(v_user_id,p_profile_id);v_user_b:=greatest(v_user_id,p_profile_id);if exists(select 1 from public.likes where liker_id=p_profile_id and liked_id=v_user_id) then insert into public.matches(user_a,user_b) values(v_user_a,v_user_b) on conflict(user_a,user_b) do nothing returning id into v_match_id;if v_match_id is null then select id into v_match_id from public.matches where user_a=v_user_a and user_b=v_user_b;end if;return query select true,v_match_id;return;end if;return query select false,null::uuid;end;$function$;

create or replace function public.send_superlike(p_recipient_id uuid) returns boolean language plpgsql security definer set search_path=public as $function$
declare v_sender uuid:=auth.uid();v_balance integer;v_superlike_id uuid;
begin if v_sender is null then raise exception 'AUTH_REQUIRED';end if;if v_sender=p_recipient_id then raise exception 'INVALID_PROFILE';end if;if not exists(select 1 from public.profiles where id=p_recipient_id and profile_completed=true and ghost_mode=false) then raise exception 'PROFILE_UNAVAILABLE';end if;if exists(select 1 from public.blocks where (blocker_id=v_sender and blocked_id=p_recipient_id) or (blocker_id=p_recipient_id and blocked_id=v_sender)) then raise exception 'USER_UNAVAILABLE';end if;select purchased_superlikes into v_balance from public.superlike_wallets where user_id=v_sender for update;if coalesce(v_balance,0)<1 then raise exception 'SUPERLIKE_EMPTY';end if;if exists(select 1 from public.superlikes where sender_id=v_sender and recipient_id=p_recipient_id) then raise exception 'ALREADY_SENT';end if;insert into public.superlikes(sender_id,recipient_id) values(v_sender,p_recipient_id) returning id into v_superlike_id;update public.superlike_wallets set purchased_superlikes=purchased_superlikes-1,updated_at=now() where user_id=v_sender;insert into public.extrovert_token_wallets(user_id,balance) values(p_recipient_id,1) on conflict(user_id) do update set balance=extrovert_token_wallets.balance+1,updated_at=now();insert into public.extrovert_token_ledger(user_id,amount,reason,source_superlike_id) values(p_recipient_id,1,'received_superlike',v_superlike_id);return true;end;$function$;
