import { cn } from "@/lib/utils";
import { type ButtonHTMLAttributes, forwardRef, memo } from "react";
import { Loader2 } from "lucide-react";

type ButtonVariant="primary"|"secondary"|"outline"|"ghost"|"destructive"|"gradient"; type ButtonSize="sm"|"md"|"lg";
interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement>{variant?:ButtonVariant;size?:ButtonSize;isLoading?:boolean;leftIcon?:React.ReactNode;rightIcon?:React.ReactNode}
const variants:Record<ButtonVariant,string>={primary:"bg-emerald-600 text-white shadow-sm shadow-emerald-600/20 hover:bg-emerald-500",secondary:"border border-emerald-100 bg-emerald-50 text-emerald-800 hover:bg-emerald-100",outline:"border border-zinc-200 bg-white text-zinc-800 shadow-sm hover:border-emerald-200 hover:bg-emerald-50/50",ghost:"bg-transparent text-zinc-600 hover:bg-emerald-50 hover:text-emerald-700",destructive:"bg-rose-600 text-white shadow-sm shadow-rose-600/15 hover:bg-rose-500",gradient:"bg-gradient-to-r from-emerald-600 to-teal-600 text-white shadow-md shadow-emerald-600/20 hover:from-emerald-500 hover:to-teal-500"};
const sizes:Record<ButtonSize,string>={sm:"h-9 rounded-xl px-3 text-xs gap-1.5",md:"h-11 rounded-2xl px-4 text-xs font-bold gap-2",lg:"h-12 rounded-2xl px-5 text-sm font-bold gap-2.5"};
export const Button=memo(forwardRef<HTMLButtonElement,ButtonProps>(({className,variant="primary",size="md",disabled,isLoading=false,leftIcon,rightIcon,children,type="button",...props},ref)=>{const off=disabled||isLoading;return <button ref={ref} type={type} disabled={off} className={cn("relative inline-flex items-center justify-center overflow-hidden font-sans font-bold tracking-tight select-none cursor-pointer transform-gpu transition-[background-color,border-color,box-shadow,transform,opacity] duration-150 ease-out focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500/30 focus-visible:ring-offset-2 active:scale-[.975] disabled:pointer-events-none disabled:cursor-wait disabled:opacity-55",isLoading&&"smart-loading",variants[variant],sizes[size],className)} {...props}>{isLoading?<Loader2 className="h-4 w-4 shrink-0 animate-spin"/>:leftIcon&&<span className="shrink-0 flex items-center">{leftIcon}</span>}{children&&<span className="truncate">{children}</span>}{!isLoading&&rightIcon&&<span className="shrink-0 flex items-center">{rightIcon}</span>}</button>}));
Button.displayName="Button";
export type { ButtonProps };
