import { cn } from "@/lib/utils";
import { forwardRef, type HTMLAttributes } from "react";
type CardProps=HTMLAttributes<HTMLDivElement>;
export const Card=forwardRef<HTMLDivElement,CardProps>(({className,children,...props},ref)=><div ref={ref} className={cn("rounded-[1.75rem] border border-zinc-200/80 bg-white p-4 font-sans shadow-[0_6px_24px_rgba(15,23,42,.045)] sm:p-5",className)} {...props}>{children}</div>);
Card.displayName="Card";
export const CardHeader=forwardRef<HTMLDivElement,CardProps>(({className,children,...props},ref)=><div ref={ref} className={cn("mb-4 space-y-1.5",className)} {...props}>{children}</div>);CardHeader.displayName="CardHeader";
export const CardTitle=forwardRef<HTMLHeadingElement,HTMLAttributes<HTMLHeadingElement>>(({className,children,...props},ref)=><h3 ref={ref} className={cn("text-base font-black tracking-tight text-zinc-950",className)} {...props}>{children}</h3>);CardTitle.displayName="CardTitle";
export const CardDescription=forwardRef<HTMLParagraphElement,HTMLAttributes<HTMLParagraphElement>>(({className,children,...props},ref)=><p ref={ref} className={cn("text-xs font-medium leading-relaxed text-zinc-500",className)} {...props}>{children}</p>);CardDescription.displayName="CardDescription";
export const CardContent=forwardRef<HTMLDivElement,CardProps>(({className,children,...props},ref)=><div ref={ref} className={cn("w-full",className)} {...props}>{children}</div>);CardContent.displayName="CardContent";
export const CardFooter=forwardRef<HTMLDivElement,CardProps>(({className,children,...props},ref)=><div ref={ref} className={cn("mt-5 flex items-center justify-between border-t border-zinc-100 pt-4",className)} {...props}>{children}</div>);CardFooter.displayName="CardFooter";
