import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { redirect } from "next/navigation";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { routes } from "@/config/routes";
import { getProfilePhotoUrl } from "@/lib/profile-photo";
import { calculateAge } from "@/lib/utils";
import { Edit3, Settings, MapPin, ShieldCheck, Star, SlidersHorizontal, Eye, EyeOff } from "lucide-react";

export const metadata: Metadata = { title: "Profile | Extrovert" };
export const dynamic = "force-dynamic";

type ProfileInterest = { id: string; name: string };
type ProfileInterestRow = { interests?: ProfileInterest | ProfileInterest[] | null };
function TrustBadge({ ok, yes, no }: { ok: boolean; yes: string; no: string }) { return <span className={`inline-flex items-center gap-1 rounded-full border px-2 py-1 text-[9px] font-bold ${ok ? "border-emerald-500/25 bg-emerald-500/10 text-emerald-300" : "border-white/10 bg-white/5 text-white/45"}`}><ShieldCheck className="h-2.5 w-2.5" />{ok ? yes : no}</span>; }

export default async function ProfilePage() {
  const supabase = await createServerSupabaseClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect(routes.login);
  const [{ data: profile }, { data: preferences }, { data: identity }] = await Promise.all([
    supabase.from("profiles").select("id,bio,profile_completed,ghost_mode,campus_residency,campus_hangout,relationship_goal,zodiac,sleep_habit,caffeine_pref,weekend_vibe,prompt_question,prompt_answer,profile_photos(id,storage_path,is_primary,display_order),profile_interests(interests(id,name))").eq("id", user.id).maybeSingle(),
    supabase.from("dating_preferences").select("interested_in,min_age,max_age,preferred_department").eq("user_id", user.id).maybeSingle(),
    supabase.from("extrovert_profiles").select("display_name,date_of_birth,gender,identity_type,institution_name,field_of_study,department,academic_year,job_title,employer_name,role_description,verification_status,area_verification_status,area_id,profile_photo_path").eq("id", user.id).maybeSingle(),
  ]);
  if (!profile?.profile_completed || !identity) redirect(routes.profileSetup);
  const photos = [...(profile.profile_photos ?? [])].sort((a, b) => a.display_order - b.display_order);
  const photoUrls = photos.map((p) => getProfilePhotoUrl(p.storage_path, 480)).filter(Boolean) as string[];
  const sharedPhoto = getProfilePhotoUrl(identity.profile_photo_path, 480);
  const primaryPhoto = photoUrls[0] ?? sharedPhoto;
  const age = identity.date_of_birth ? calculateAge(identity.date_of_birth) : null;
  const interestRows = (profile.profile_interests ?? []) as ProfileInterestRow[];
  const interests = interestRows.flatMap((pi) => pi.interests ? (Array.isArray(pi.interests) ? pi.interests : [pi.interests]) : []);
  const showMe = preferences?.interested_in?.includes("everyone") || ((preferences?.interested_in?.includes("men") ?? false) && (preferences?.interested_in?.includes("women") ?? false)) ? "Everyone" : preferences?.interested_in?.[0] ? preferences.interested_in[0].replace(/^./, (c: string) => c.toUpperCase()) : "Everyone";
  const areaResult = identity.area_id ? await supabase.from("extrovert_areas").select("name").eq("id", identity.area_id).maybeSingle() : null;
  const isStudent = identity.identity_type === "student";
  const context = isStudent ? `${identity.institution_name || "College / university"} · ${identity.department || "Student"}${identity.academic_year ? ` · ${identity.academic_year}` : ""}` : identity.identity_type === "professional" ? `${identity.job_title || "Professional"}${identity.employer_name ? ` · ${identity.employer_name}` : ""}` : (identity.role_description || "Current role");

  return <main className="mx-auto max-w-md space-y-3.5 px-3.5 pb-24 pt-16 font-sans text-white md:pt-4 md:text-zinc-950">
    <div className="flex items-center justify-between px-1"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-pink-400 md:text-emerald-600">YOU</p><h1 className="text-2xl font-black tracking-tight">Your profile</h1></div><div className="flex items-center gap-2"><Link href={routes.profileSetup} className="flex items-center gap-1.5 rounded-full bg-white px-4 py-2 text-xs font-bold text-black"><Edit3 className="h-3.5 w-3.5" />Edit</Link><Link href={routes.settings} aria-label="Settings" className="grid h-9 w-9 place-items-center rounded-full bg-zinc-900 text-white md:bg-zinc-100 md:text-zinc-700"><Settings className="h-4 w-4" /></Link></div></div>
    <section className="overflow-hidden rounded-[2rem] border border-white/10 bg-zinc-950 shadow-2xl md:border-zinc-200 md:bg-white md:shadow-sm"><div className="relative aspect-[4/5] max-h-[520px] w-full bg-zinc-900">{primaryPhoto ? <Image src={primaryPhoto} alt={identity.display_name ?? "Profile"} fill priority decoding="async" className="object-cover" sizes="(max-width:640px) 100vw,448px"/>:<div className="flex h-full items-center justify-center text-6xl font-black text-white/20">{identity.display_name?.charAt(0)??"?"}</div>}<div className="absolute inset-0 bg-gradient-to-t from-black via-transparent to-black/10"/><div className="absolute inset-x-0 bottom-0 p-5"><div className="flex flex-wrap items-center gap-2"><h2 className="text-3xl font-black">{identity.display_name||"Member"}{age!==null&&<span className="ml-1 font-light">, {age}</span>}</h2>{identity.verification_status==="verified"&&<span className="grid h-7 w-7 place-items-center rounded-full bg-white text-emerald-600"><ShieldCheck className="h-4 w-4"/></span>}</div><p className="mt-1 text-xs font-semibold text-white/80">{context}</p>{areaResult?.data?.name&&<p className="mt-1 flex items-center gap-1 text-[10px] text-white/60"><MapPin className="h-3 w-3"/>{areaResult.data.name}</p>}</div></div><div className="p-4"><div className="flex flex-wrap gap-1.5"><TrustBadge ok={identity.verification_status === "verified"} yes="Identity verified" no="Identity not verified"/><TrustBadge ok={identity.area_verification_status === "verified"} yes="Area verified" no="Area not verified"/></div>{profile.bio&&<p className="mt-3 text-sm leading-6 text-white/80 md:text-zinc-700">&ldquo;{profile.bio}&rdquo;</p>}</div></section>
    {photoUrls.length>0&&<section className="rounded-[1.75rem] border border-white/10 bg-zinc-950 p-3.5 md:border-zinc-200 md:bg-white"><div className="mb-2 flex items-center justify-between"><span className="text-[10px] font-black uppercase tracking-wider text-white/45 md:text-zinc-500">Dating photos · {photoUrls.length}/6</span><Link href={routes.profileSetup} className="text-[10px] font-bold text-pink-400 md:text-emerald-600">Update</Link></div><div className="grid grid-cols-3 gap-2">{photoUrls.map((url,i)=><div key={i} className="relative aspect-[4/5] overflow-hidden rounded-2xl bg-zinc-900"> <Image src={url} alt={`Dating photo ${i+1}`} fill decoding="async" className="object-cover" sizes="(max-width:640px) 30vw,140px"/>{i===0&&<span className="absolute left-1 top-1 rounded-full bg-black/60 px-1.5 py-0.5 text-[8px] font-bold text-white"><Star className="mr-0.5 inline h-2 w-2 fill-current"/>Main</span>}</div>)}</div></section>}
    <section className="grid grid-cols-2 gap-2"><div className="rounded-2xl border border-white/10 bg-zinc-950 p-3 md:border-zinc-200 md:bg-white"><div className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wider text-white/45 md:text-zinc-500"><SlidersHorizontal className="h-3 w-3 text-pink-400 md:text-emerald-600"/>Matching</div><span className="mt-1 block truncate text-xs font-bold">{showMe}</span><span className="text-[10px] text-white/40 md:text-zinc-500">{preferences?.min_age??18}–{preferences?.max_age??25} yrs</span></div><Link href={routes.settings} className="rounded-2xl border border-white/10 bg-zinc-950 p-3 md:border-zinc-200 md:bg-white"><div className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wider text-white/45 md:text-zinc-500">{profile.ghost_mode?<EyeOff className="h-3 w-3 text-amber-400"/>:<Eye className="h-3 w-3 text-emerald-400"/>}Visibility</div><span className="mt-1 block text-xs font-bold">{profile.ghost_mode?"Ghost Mode":"Public"}</span><span className="text-[10px] text-white/40 md:text-zinc-500">{profile.ghost_mode?"Hidden from deck":"Active in Swipe"}</span></Link></section>
    {(profile.relationship_goal||profile.zodiac||profile.sleep_habit||profile.caffeine_pref||profile.weekend_vibe)&&<section className="rounded-2xl border border-white/10 bg-zinc-950 p-4 md:border-zinc-200 md:bg-white"><span className="text-[10px] font-black uppercase tracking-wider text-white/45 md:text-zinc-500">Dating vibe</span><div className="mt-2 flex flex-wrap gap-1.5">{[profile.relationship_goal,profile.zodiac,profile.sleep_habit,profile.caffeine_pref,profile.weekend_vibe].filter(Boolean).map(x=><span key={x} className="rounded-full bg-white/10 px-2.5 py-1 text-[11px] font-bold md:bg-zinc-100">{x}</span>)}</div></section>}
    {interests.length>0&&<section className="rounded-2xl border border-white/10 bg-zinc-950 p-4 md:border-zinc-200 md:bg-white"><span className="text-[10px] font-black uppercase tracking-wider text-white/45 md:text-zinc-500">Interests</span><div className="mt-2 flex flex-wrap gap-1.5">{interests.map(i=><span key={i.id} className="rounded-full bg-white/10 px-2.5 py-1 text-[11px] md:bg-zinc-100">{i.name}</span>)}</div></section>}
    {profile.prompt_question&&profile.prompt_answer&&<section className="rounded-2xl border border-white/10 bg-zinc-950 p-4 md:border-zinc-200 md:bg-white"><span className="text-[10px] font-black uppercase tracking-wider text-pink-400 md:text-emerald-600">Prompt</span><p className="mt-1 text-sm font-bold">{profile.prompt_question}</p><p className="mt-1 text-sm text-white/70 md:text-zinc-600">&ldquo;{profile.prompt_answer}&rdquo;</p></section>}
  </main>;
}
